### ISSUE TITLE
在线播放使用mpc-be显示没有找到文件

### ISSUE THREAD

**Issue by ROOOCCCK** [gaozhangmin/aliyunpan#10]

**Comment by gaozhangmin** [comment]
设置里设置了自定义播放器了吗

**Comment by ROOOCCCK** [comment]
> 设置里设置了自定义播放器了吗

设置了才会知道显示没找到文件呀，确实不行，你可以试试看

**Comment by ROOOCCCK** [comment]
> > > 设置里设置了自定义播放器了吗
> > 
> > 
> > 设置了才会知道显示没找到文件呀，确实不行，你可以试试看
> 
> 是windows吗？

只有windows才能用mpc-be mpc-hc这种播放器，跟pot差不多，你这里支持pot但不支持mpc就很奇怪

**Comment by gaozhangmin** [comment]
> > > > 设置里设置了自定义播放器了吗
> > > 
> > > 
> > > 设置了才会知道显示没找到文件呀，确实不行，你可以试试看
> > 
> > 
> > 是windows吗？
> 
> 只有windows才能用mpc-be mpc-hc这种播放器，跟pot差不多，你这里支持pot但不支持mpc就很奇怪

没windows电脑 无法测试啊。我支试过mac没问题。
