### ISSUE TITLE
M2 Mac mini版小白羊v3.11.5 Aria2本地连接已断开

### ISSUE THREAD

**Issue by aaaenenen** [gaozhangmin/aliyunpan#100]
![CleanShot 2023-04-21 at 09 08 47](https://user-images.githubusercontent.com/131418306/233520001-ea2664ce-f36c-4b4c-b381-5de20e66118b.png)
![CleanShot 2023-04-21 at 09 13 40](https://user-images.githubusercontent.com/131418306/233520014-be3a8487-db8b-4e81-927f-606c34152cc2.png)
![CleanShot 2023-04-21 at 09 16 05](https://user-images.githubusercontent.com/131418306/233520026-891de5c0-aa06-486f-bd6e-dca62fcaccdb.png)
![CleanShot 2023-04-21 at 09 35 27](https://user-images.githubusercontent.com/131418306/233520057-7e1eb7e4-89ca-4816-bf48-ac54c64f19b3.png)

**Comment by jimmieyangcsjs** [comment]
你没装aria2 肯定会报错 看看说明好不？

**Comment by aaaenenen** [comment]
求大神指条明路，不会安装aria2啊，在哪下载，然后咋安装啊？

**Comment by aaaenenen** [comment]
> 你没装aria2 肯定会报错 看看说明好不？
求大神指条明路，不会安装aria2啊，在哪下载，然后咋安装啊？

**Comment by aaaenenen** [comment]
大哥，能指点一二吗，我不知道咋装的，aria2要在哪里下？




禾倩婷
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaozhangmin/aliyunpan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaozhangmin/aliyunpan] M2 Mac mini版小白羊v3.11.5 Aria2本地连接已断开 (Issue #100)





 
你没装aria2 肯定会报错 看看说明好不？

**Comment by jimmieyangcsjs** [comment]
> 大哥，能指点一二吗，我不知道咋装的，aria2要在哪里下？ 禾倩婷 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gaozhangmin/aliyunpan" ***@***.***&gt;; 发送时间:&nbsp;2023年4月21日(星期五) 上午10:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gaozhangmin/aliyunpan] M2 Mac mini版小白羊v3.11.5 Aria2本地连接已断开 (Issue #100) 你没装aria2 肯定会报错 看看说明好不？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

先装brew  然后brew install

**Comment by 998137217749** [comment]
> > 大哥，能指点一二吗，我不知道咋装的，aria2要在哪里下？ 禾倩婷 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "gaozhangmin/aliyunpan" _**@**_._**>; 发送时间: 2023年4月21日(星期五) 上午10:28 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [gaozhangmin/aliyunpan] M2 Mac mini版小白羊v3.11.5 Aria2本地连接已断开 (Issue #100) 你没装aria2 肯定会报错 看看说明好不？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 先装brew 然后brew install

你这种就跟啥都没说一样
