### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by wuyaos** [gaozhangmin/aliyunpan#103]
日志
```
21 11:14:22 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:39349)
    at IDBTransaction.<anonymous> (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:6227)
21 11:14:22 : danger : unhandledrejection
21 11:14:22 : danger : unhandledrejection 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at tempTransaction (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:10096)
    at C._trans (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:12139)
    at C.put (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:15773)
    at XBYDB3.saveValueString (file:///C:/Program%20Files...
21 11:14:22 : danger : unhandledrejection
```
登录报错，一直卡在用户信息刷新中
<img width="697" alt="Snipaste_2023-04-21_11-18-56" src="https://user-images.githubusercontent.com/19622399/233533004-0f05f00e-db70-48d4-8c88-b02f08632dc0.png">
我用其他人的电脑却可以登录

**Comment by LoserForever88** [comment]
+1 我也有这个问题

**Comment by gaozhangmin** [comment]
> 日志
> 
> ```
> 
> 21 11:14:22 : danger : unhandledrejection 
> 
> //== Error ==//
> 
>  Transaction aborted 
> 
> //== Stack ===//
> 
>  AbortError: Transaction aborted
> 
>     at IDBTransaction.<anonymous> (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:39349)
> 
>     at IDBTransaction.<anonymous> (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:6227)
> 
> 21 11:14:22 : danger : unhandledrejection
> 
> 21 11:14:22 : danger : unhandledrejection 
> 
> //== Error ==//
> 
>  UpgradeError Not yet support for changing primary key 
> 
> //== Stack ===//
> 
>  DatabaseClosedError: UpgradeError Not yet support for changing primary key
> 
>     at tempTransaction (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:10096)
> 
>     at C._trans (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:12139)
> 
>     at C.put (file:///C:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:15773)
> 
>     at XBYDB3.saveValueString (file:///C:/Program%20Files...
> 
> 21 11:14:22 : danger : unhandledrejection
> 
> ```
> 
> 登录报错，一直卡在用户信息刷新中
> 
> <img width="697" alt="Snipaste_2023-04-21_11-18-56" src="https://user-images.githubusercontent.com/19622399/233533004-0f05f00e-db70-48d4-8c88-b02f08632dc0.png">
> 
> 我用其他人的电脑却可以登录
你把缓存再试试吧，你这是第一次安装3.11.5版本吗
