### ISSUE TITLE
上传功能挂了，任何文件都无法上传！

### ISSUE THREAD

**Issue by snow212-cn** [gaozhangmin/aliyunpan#105]
![image](https://user-images.githubusercontent.com/18443918/233756190-8da0eefc-23f0-4ee1-8b2b-7c3d1ec75d8c.png)

**Comment by gaozhangmin** [comment]
你能把你的文件夹层次发下吗 我本地没有发现这个bug

**Comment by jzx765** [comment]
我也一样，下午开始，无法上传了，试验了官方版，正常上传
![image](https://user-images.githubusercontent.com/56497479/233782118-2b32cd8f-3ae4-40db-bd8d-42a5b195bca0.png)
![image](https://user-images.githubusercontent.com/56497479/233782127-69eb69c5-a401-4844-b513-c10af6b0cd5a.png)

**Comment by gaozhangmin** [comment]
> 我也一样，下午开始，无法上传了，试验了官方版，正常上传
> 
> ![image](https://user-images.githubusercontent.com/56497479/233782118-2b32cd8f-3ae4-40db-bd8d-42a5b195bca0.png)
> 
> ![image](https://user-images.githubusercontent.com/56497479/233782127-69eb69c5-a401-4844-b513-c10af6b0cd5a.png)
> 
> 

我感觉是少数情况，我试了上传没问题的啊

**Comment by jzx765** [comment]
> 

测试了官方版，和10.24版本，正常上传。暂时不管了，先用10.24传吧。
![image](https://user-images.githubusercontent.com/56497479/233782761-b4596308-22cf-4638-8ce7-b423613e2db3.png)
