### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by sy999999ys** [gaozhangmin/aliyunpan#106]
1. 内置播放器读取了同目录下的字幕文件，但并没有在播放器上显示字幕。
2. 内置播放器最高只有1080p，没有原画质。
3. 多账号登录失败，只能登录一个账号。

**Comment by gaozhangmin** [comment]
2. 没有原画质，是因为阿里云服务器端就没有。
3. 我没登录2个账号需求

**Comment by sy999999ys** [comment]
那其他的第三方阿里云盘是怎么做到内置播放器可以看原画质的
