### ISSUE TITLE
获取二维码失败

### ISSUE THREAD

**Issue by wylenovo** [gaozhangmin/aliyunpan#109]
第一次登录，扫描二维码后，提示获取二维码失败，退出重启

**Comment by Morning-sun102** [comment]
我也是，现在我都登不上我的账户

**Comment by Heressaza** [comment]
me too

**Comment by SouperGeng** [comment]
我也是

**Comment by LIUBANGJIAN** [comment]
me too

**Comment by LIUBANGJIAN** [comment]
完全卸载都没用。

**Comment by gaozhangmin** [comment]
> 完全卸载都没用。
 
晚上发版解决

**Comment by Joackk** [comment]
@gaozhangmin 大佬这个问题似乎又出现了，昨天还正常，今天突然就提示了这个
![image](https://github.com/gaozhangmin/aliyunpan/assets/45162558/ecfd979a-e979-4dc9-9f80-c91c6979b910)

**Comment by oasis-0927** [comment]
> @gaozhangmin 大佬这个问题似乎又出现了，昨天还正常，今天突然就提示了这个 ![image](https://private-user-images.githubusercontent.com/45162558/326180611-ecfd979a-e979-4dc9-9f80-c91c6979b910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDU0MTEsIm5iZiI6MTcxNjU0NTExMSwicGF0aCI6Ii80NTE2MjU1OC8zMjYxODA2MTEtZWNmZDk3OWEtZTk3OS00ZGM5LTlmODAtYzkxYzY5NzliOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEwMDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTczMmE5ZDMyMjE3MGU2OGQ0OGFkOTFkYWM4MzM4OTQ3YTQyYTc4OTkyYTE1NmY5MWY3Y2M1ZjIyOWE1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4neEo2JltFoIlWcvROWsRgL34L88euVNJSY4upujYdY)

me too
