### ISSUE TITLE
怎么能关掉这个提示呢？

### ISSUE THREAD

**Issue by aofly** [gaozhangmin/aliyunpan#11]
![image](https://user-images.githubusercontent.com/129035806/229464260-14f2da1f-798f-49de-a4d9-7d17853b7480.png)

**Comment by gaozhangmin** [comment]
下个版本修复

**Comment by gaozhangmin** [comment]
不过，抱这个错 你不解决。你本地也下载不了啊

**Comment by gaozhangmin** [comment]
> ![image](https://user-images.githubusercontent.com/129035806/229464260-14f2da1f-798f-49de-a4d9-7d17853b7480.png)
> 
> 

已修复
