### ISSUE TITLE
什么东西 吃相这么难看？ 

### ISSUE THREAD

**Issue by lukesyy** [gaozhangmin/aliyunpan#110]
也没见你给原作者资助资助 你是真恶心

**Comment by gaozhangmin** [comment]
> 也没见你给原作者资助资助 你是真恶心

也没见你给我资助，你有什么脸bb的

**Comment by lukesyy** [comment]
脸皮是真的厚

**Comment by gaozhangmin** [comment]
> 脸皮是真的厚

给我滚远点，我吃什么了？吃你妈脑子了吗。我他妈又没靠这搞过一分钱。完全开源的。

**Comment by lukesyy** [comment]
呦呦呦 自己臭不要脸 自己还急的不行

**Comment by gaozhangmin** [comment]
> 呦呦呦 自己臭不要脸 自己还急的不行

你来这给老子正义凛然呢？原作者都没说啥，关你屌丝
