### ISSUE TITLE
最新3.11.5修复版列出文件夹报错401

### ISSUE THREAD

**Issue by Andyqi0076** [gaozhangmin/aliyunpan#111]
_FileListOnePage err=6191e7d9967afd84e4d749359f6c8b2d27c268d0 401
ApiUserDriveFileCount err= 404
_FileListOnePage err=root 401
ApiUserInfo err=401
ApiUserPic err=401
不知道是不是我这里单独的问题，现在打开3.11.5修复版无法正常加载文件，麻烦大佬看一下吧，谢谢~

**Comment by gaozhangmin** [comment]
token不对呗。

**Comment by Andyqi0076** [comment]
> 

大佬，重新获取token登录了一次，还是不行，侧边栏是有文件夹展示的，但是右侧列表空，提示还是列出文件夹失败401，windows10

**Comment by gaozhangmin** [comment]
token不对 不是从官网获取

**Comment by cwtbr** [comment]
> token不对 不是从官网获取

那是去哪里获取，麻烦告知一下
从官网拿的access_token就是没法加载文件列表

**Comment by gaozhangmin** [comment]
> > token不对 不是从官网获取
> 
> 
> 
> 那是去哪里获取，麻烦告知一下
> 
> 从官网拿的access_token就是没法加载文件列表

有很多公开的软件可以拿到自己账户的access_token的。

**Comment by cwtbr** [comment]
401的报错，是请求用户的token这个接口的时候，所有的Body请求参数和Headers都一样，但是就是报错401。喊了后端过来看了好久哈哈哈，忘了加Authorization这个请求Header了。解决办法就是，在Headers中添加基本认证的键值对。这个键值对如下：

Authorization:Basic YKKOw9MPlY3JldA==（注意：这里的Base64位编码我随便写的，可以随意看看）

**Comment by cwtbr** [comment]
> > > token不对 不是从官网获取
> > 
> > 
> > 那是去哪里获取，麻烦告知一下
> > 从官网拿的access_token就是没法加载文件列表
> 
> 有很多公开的软件可以拿到自己账户的access_token的。

我感觉就是headers中没有添加基本认证的键值对

**Comment by cwtbr** [comment]
> > > token不对 不是从官网获取
> > 
> > 
> > 那是去哪里获取，麻烦告知一下
> > 从官网拿的access_token就是没法加载文件列表
> 
> 有很多公开的软件可以拿到自己账户的access_token的。

照你这种说法，access_token的源头肯定来自官方。那说明从官方拿的access_token更行了

**Comment by cwtbr** [comment]
> > > token不对 不是从官网获取
> > 
> > 
> > 那是去哪里获取，麻烦告知一下
> > 从官网拿的access_token就是没法加载文件列表
> 
> 有很多公开的软件可以拿到自己账户的access_token的。

你直接说，你那边可以获取到文件列表吗？

**Comment by yhhdlcool** [comment]
ReFresh_Token 和access token 有啥区别？我获取的都是refresh token

**Comment by Andyqi0076** [comment]
> ReFresh_Token 和access token 有啥区别？我获取的都是refresh token

我都试了。。。还是没能解决问题

**Comment by rosspsp** [comment]
> token不对 不是从官网获取

请问一下access_token从哪里获取？

**Comment by cwtbr** [comment]
> > token不对 不是从官网获取
> 
> 请问一下access_token从哪里获取？

先登录阿里云盘。F12进入控制台，找到application，点击会出现列表。找到列表中token，点击后下面就会有的

**Comment by cwtbr** [comment]
> > token不对 不是从官网获取
> 
> 请问一下access_token从哪里获取？

点击application后先看左下方的 local storage。把它点开，再点击里面那个网址名称的东西

**Comment by rosspsp** [comment]
> 

试了，这个access_token不对。我用alist，是要扫码获取refresh_token，但试了，也不行。

**Comment by cwtbr** [comment]
> 

我感觉第一次扫码是为了获取refresh_token。第二次手动输入access_token。所以两个token都需要。
access_token 过期后, 可以使用 refresh_token 重新获取, 而 refresh_token 过期后就只能重新授权了

**Comment by GARNET-CRO** [comment]
> > > token不对 不是从官网获取
> > 
> > 
> > 请问一下access_token从哪里获取？
> 
> 点击application后先看左下方的 local storage。把它点开，再点击里面那个网址名称的东西

试了，还是显示无法正常加载文件

**Comment by yhhdlcool** [comment]
都试了，列表401错误

**Comment by GARNET-CRO** [comment]
这只能等修复么？

**Comment by cwtbr** [comment]
> > > > token不对 不是从官网获取
> > > 
> > > 
> > > 请问一下access_token从哪里获取？
> > 
> > 
> > 点击application后先看左下方的 local storage。把它点开，再点击里面那个网址名称的东西
> 
> 试了，还是显示无法正常加载文件

莫得办法。看了一下源码。再参考了网上说401报错解决办法就是   Headers中添加基本认证的键值对。
这种常见的问题，还是交给作者吧。我压根没涉及这一块。等作者更新吧。

**Comment by cwtbr** [comment]
睡了睡了。还是狗命要紧

**Comment by GARNET-CRO** [comment]
那就等等吧，睡了睡了

**Comment by zksd2022** [comment]
列表错误401  希望继续修复！

**Comment by gaozhangmin** [comment]
> 列表错误401  希望继续修复！ 

你进群 群里有怎么获取token

**Comment by rosspsp** [comment]
> 

qq？群号是？

**Comment by onleem** [comment]
网上找的获取token的方法都试了，不管是refresh_token还是access_token，都是列表错误401，只有文件夹，文件加载不出来

**Comment by pf090745** [comment]
> 网上找的获取token的方法都试了，不管是refresh_token还是access_token，都是列表错误401，只有文件夹，文件加载不出来

和你一样的问题的人不在少数

**Comment by vipcrack** [comment]
同样的问题，放映室里能扫描到所有的视频，但是网盘列表只有左边的目录，右边没东西，提示错误，而且放映室里列出来的文件也无法播放，直接黑屏。

**Comment by wanghuisenior** [comment]
同求，  在官网控制台找到的accesstoken也不行，一样的情况

**Comment by LIUBANGJIAN** [comment]
要不就直接弹出地址，让用户自己打开网页。ui也没有之前简洁，感觉开始臃肿了。

**Comment by rosspsp** [comment]
> 同求， 在官网控制台找到的accesstoken也不行，一样的情况

看我最新发布的issuse，“access_token保姆级获取教程”

**Comment by rosspsp** [comment]
> > > token不对 不是从官网获取
> > 
> > 
> > 请问一下access_token从哪里获取？
> 
> 先登录阿里云盘。F12进入控制台，找到application，点击会出现列表。找到列表中token，点击后下面就会有的
问题已解决，看我最新发布的issuse，“access_token保姆级获取教程”

**Comment by Heressaza** [comment]
列表错误401 希望继续修复！

**Comment by fgr178707** [comment]
#114

**Comment by wanghuisenior** [comment]
> 

https://alist.nn.ci/tool/aliyundrive/request.html   在这里获取到了 ，测试能用

**Comment by fgr178707** [comment]
> > 
> 
> https://alist.nn.ci/tool/aliyundrive/request.html 在这里获取到了 ，测试能用

你如果在电报群里的话，你应该能看见我发过全套的教程。

**Comment by AjianYo** [comment]
> > https://alist.nn.ci/tool/aliyundrive/request.html 在这里获取到了 ，测试能用
> 
> 你如果在电报群里的话，你应该能看见我发过全套的教程。 ![image](https://user-images.githubusercontent.com/109357981/234161729-79015268-08b6-46e4-98db-9b6d7f3916a8.png)

太强了，非常细致，感谢感谢

**Comment by LIUBANGJIAN** [comment]
token文件解决不了的话，感觉这个软件到陌路了。

**Comment by LIUBANGJIAN** [comment]
> token文件解决不了的话，感觉这个软件到陌路了。

末

**Comment by m-dnxbf** [comment]
也发生了同一个问题，用的是access_token，在官方网站上找到的

**Comment by shuai274** [comment]
我也是，按照上面的步骤还是显示列出文件夹失败
