### ISSUE TITLE
access_token保姆级获取教程

### ISSUE THREAD

**Issue by rosspsp** [gaozhangmin/aliyunpan#114]
准备：chrome浏览器
1、打开网址：https://alist.nn.ci/tool/aliyundrive/request.html
2、点击“Go to login”按钮
![微信截图_20230424085700](https://user-images.githubusercontent.com/73610222/233877916-16950994-5a66-4451-a93c-45430654f3b8.png)
3、在新打开的页面按F12，并按红框定位
![微信截图_20230424085629](https://user-images.githubusercontent.com/73610222/233877927-6a49f4fe-0222-48ea-82bf-c85897d3fcfc.png)
4、阿里云盘APP扫码，手机上点击“确认并登陆”，chrome上点击“允许”，按图中红框定位即可找到access_token
![微信截图_20230424090238](https://user-images.githubusercontent.com/73610222/233878320-1c72ed75-4667-4fa3-9353-70c8ddd69d1c.png)

PS:
1、这个access_token是你专属的，请不要透露给任何人。
2、chrome最好清一下cookies，复制access_token不能带引号
3、作者的公众号中说，这个token只有三个小时有效期，三个小时到期后，好像还得填写一下，目前还没有测试。
![233882773-e8e6fe65-afc4-4edd-8721-68456721d594](https://user-images.githubusercontent.com/73610222/233884449-15cb3bc7-3b98-4652-b6a4-bf18121b2e20.png)

**Comment by RinSky123** [comment]
试了，登不上去，获取文件夹失败

**Comment by rosspsp** [comment]
> 试了，登不上去，获取文件夹失败

chrome最好清一下cookies，复制access_token不能带引号

**Comment by yhhdlcool** [comment]
昨天都试了，没用

**Comment by yhhdlcool** [comment]
这是Refresh Token ，不是access token。你不会是骗子，骗账号的吧

**Comment by rosspsp** [comment]
> 这是Refresh Token ，不是access token。你不会是骗子，骗账号的吧

看图，好吗？

**Comment by y7788210** [comment]
可以，解决了，谢谢大佬！

**Comment by rosspsp** [comment]
> 这是Refresh Token ，不是access token。你不会是骗子，骗账号的吧

说话积点口德好不好？你可以不用看，不要污蔑人。没人强制你！！！！！！！！！你个破账号，你觉得我瞧得上吗？

**Comment by rosspsp** [comment]
我看作者的公众号中，说这个token只有三个小时有效期，三个小时到期后，好像还得填写一下，目前还没有测试。
![微信截图_20230424100140](https://user-images.githubusercontent.com/73610222/233882773-e8e6fe65-afc4-4edd-8721-68456721d594.png)

**Comment by rosspsp** [comment]
> 可以了，感谢！ ![屏幕截图 2023-04-24 095914](https://user-images.githubusercontent.com/97228021/233882673-f868de7f-88d9-4ef6-96e2-0a37a87bcc52.png)

嗯嗯

**Comment by yhhdlcool** [comment]
测试了一下，确实能用了，向rosspsp道歉。冤枉你了

**Comment by shemengjia** [comment]
谢谢大佬成功了，用chrome，edge全特么中文看不懂

**Comment by rosspsp** [comment]
> 谢谢大佬成功了，用chrome，edge全特么中文看不懂

对，要用chrome

**Comment by rosspsp** [comment]
> 测试了一下，确实能用了，向rosspsp道歉。冤枉你了

可以了就行。发这个issues，我也是好心，作者这个问题上没有太详细说明，是因为有自己的顾虑，我也是希望这个项目越来越好。

**Comment by aaaenenen** [comment]
M2 Mac mini前来报道，设置成功，特来感谢！
![CleanShot 2023-04-24 at 10 41 19](https://user-images.githubusercontent.com/131418306/233889270-e349e19c-1f0d-4683-ac6d-86b078c0e4b1.png)
![CleanShot 2023-04-24 at 10 39 26](https://user-images.githubusercontent.com/131418306/233889401-43d5b18d-cb0e-46c8-867b-7498db39aeeb.png)
![CleanShot 2023-04-24 at 10 42 24](https://user-images.githubusercontent.com/131418306/233889425-8204372e-3a03-4113-8e5b-f398635bf28c.png)
![CleanShot 2023-04-24 at 10 45 23](https://user-images.githubusercontent.com/131418306/233889431-91678758-e470-48e3-a59f-8a7e18e49660.png)

**Comment by rosspsp** [comment]
> M2 Mac mini前来报道，设置成功，特来感谢！ ![CleanShot 2023-04-24 at 10 41 19](https://user-images.githubusercontent.com/131418306/233889270-e349e19c-1f0d-4683-ac6d-86b078c0e4b1.png) ![CleanShot 2023-04-24 at 10 39 26](https://user-images.githubusercontent.com/131418306/233889401-43d5b18d-cb0e-46c8-867b-7498db39aeeb.png) ![CleanShot 2023-04-24 at 10 42 24](https://user-images.githubusercontent.com/131418306/233889425-8204372e-3a03-4113-8e5b-f398635bf28c.png) ![CleanShot 2023-04-24 at 10 45 23](https://user-images.githubusercontent.com/131418306/233889431-91678758-e470-48e3-a59f-8a7e18e49660.png)

safari浏览器获取token，看这里了！

**Comment by charley008** [comment]
为啥要第一步“1、打开网址：https://alist.nn.ci/tool/aliyundrive/request.html”，
直接网页打开https://www.aliyundrive.com/drive，f12 就能找得到。应用-本地存储空间-找到https://www.aliyundrive.com 点开token，第二行就是accesss_token
打开第一步看到要授权这个alist访问我的网盘我就不干了。

**Comment by Heressaza** [comment]
感谢！！！！！

**Comment by yhhdlcool** [comment]
已测试，token 3小时过期。但是继续用原来的token复制进去，可以继续使用。。

**Comment by LIUBANGJIAN** [comment]
可以用，但是3小时又是条好汉。

**Comment by shemengjia** [comment]
这咋用着用着就弹出过期了，难道每隔3小时就要输入？卧槽

**Comment by rosspsp** [comment]
> 已测试，token 3小时过期。但是继续用原来的token复制进去，可以继续使用。。

确实是的

**Comment by rosspsp** [comment]
> 这咋用着用着就弹出过期了，难道每隔3小时就要输入？卧槽

嗯，刚刚我的也弹了！

**Comment by feihongqiuye** [comment]
还是从根本上解决问题吧，这样会劝退很多人。大部分人想要的还是扫码登录，然后就不用管了

**Comment by aaaenenen** [comment]
> 还是从根本上解决问题吧，这样会劝退很多人。大部分人想要的还是扫码登录，然后就不用管了

我喜欢这种用access—token的！扫码还得拿手机，麻烦！而且我手机上都安装不了阿里云盘了，我就喜欢这种登录方式

**Comment by Niyankee** [comment]
> > 谢谢大佬成功了，用chrome，edge全特么中文看不懂
> 
> 对，要用chrome

额，不绑定chrome吧，edge不是一样用嘛

**Comment by rosspsp** [comment]
> > > 谢谢大佬成功了，用chrome，edge全特么中文看不懂
> > 
> > 
> > 对，要用chrome
> 
> 额，不绑定chrome吧，edge不是一样用嘛

不一定非得用chrome，无论什么浏览器，只要你能获取到access_token就行

**Comment by kratos9394** [comment]
还有期限，算了还是alist加fuse吧，之前也是这么用

**Comment by TKTick** [comment]
用这个扫码后直击点击获取就行，不用进开发者工具
https://alist.nn.ci/zh/guide/drivers/aliyundrive.html

**Comment by 957057** [comment]
为何我这登录可以但是显示列出文件失败403呢

**Comment by wanghuisenior** [comment]
> 



> 用这个扫码后直击点击获取就行，不用进开发者工具 https://alist.nn.ci/zh/guide/drivers/aliyundrive.html
你试试就知道行不行

**Comment by wanghuisenior** [comment]
> 用这个扫码后直击点击获取就行，不用进开发者工具 https://alist.nn.ci/zh/guide/drivers/aliyundrive.html

你试了么

**Comment by aaronkaiyangg** [comment]
马住，回去操作

**Comment by a525850194** [comment]
> 用这个扫码后直击点击获取就行，不用进开发者工具 https://alist.nn.ci/zh/guide/drivers/aliyundrive.html

不行 试过了

**Comment by aaronkaiyangg** [comment]
邮件已收到，会尽快回复，谢谢！

**Comment by wanghuisenior** [comment]
> 是401

还是accesstoken不对

**Comment by wanghuisenior** [comment]
这种情况的话  还是先用蜗牛云盘把   等大佬搞到开发者权限   现在过3小时就要再获取太麻烦了

**Comment by heibaigame** [comment]
马克
