### ISSUE TITLE
linux版需求

### ISSUE THREAD

**Issue by qNwNp** [gaozhangmin/aliyunpan#115]
能否麻烦作者打包一个linux版，谢谢

**Comment by Tiggy-Chan** [comment]
![2023-04-24_15-06](https://user-images.githubusercontent.com/79960316/233923425-d034ff2e-e7df-48c9-9b16-c4f860a51180.png)

**Comment by Tiggy-Chan** [comment]
> 

![2023-04-24_15-06](https://user-images.githubusercontent.com/79960316/233923493-620e90e6-01bb-4596-bd4d-3913cdb45cae.png)

**Comment by qNwNp** [comment]
> > 
> 
> ![2023-04-24_15-06](https://user-images.githubusercontent.com/79960316/233923493-620e90e6-01bb-4596-bd4d-3913cdb45cae.png)
> 

感谢
