### ISSUE TITLE
macOS 无法打开 app（提示应用已损坏），解决方法

### ISSUE THREAD

**Issue by Zilanlann** [gaozhangmin/aliyunpan#12]
解决方法

1. 允许 “任何来源” 下载的 App 运行
打开 “终端” 执行如下命令（根据提示输入您的密码即可）：

`sudo spctl --master-disable`

打开 “系统偏好设置…” - “安全性与隐私”，“通用” 标签页，如图勾选：

![Allow Anywhere](https://sysin.org/blog/macos-if-crashes-when-opening/allow-anywhere.webp)

allow-anywherep

macOS Ventura 略有变化，位于：系统设置 – 隐私和安全性，“安全性”。

![macOS Ventura](https://sysin.org/blog/macos-if-crashes-when-opening/system-setting-security.webp)

2. 移除应用的安全隔离属性
打开 “终端” 执行如下命令（根据提示输入您的密码即可）：

`sudo xattr -dr com.apple.quarantine /Applications/小白羊云盘.app`

但是如果能解决，还是期待作者解决这个问题，以免有一些安全隐患。

**Comment by gaozhangmin** [comment]
下个版本解决
