### ISSUE TITLE
安装路径带空格会一直不断的报错

### ISSUE THREAD

**Issue by cycloneblack** [gaozhangmin/aliyunpan#120]
版本：[小白羊3.11.5 - 修复登录失败](https://github.com/gaozhangmin/aliyunpan/releases/tag/3.11.5.1)
安装路径：D:\Program Files\xbyyunpan
安装完毕启动小白羊，会无限报错：
启动Aria2c失败
错误信息:Command failed: D: Program Files xbyyunpan resources\engine aria2cexe--stop-with-process=2300 -D --rpc-listen-port=16800 --conf-path="D: ProgramFiles'xbyyunpan'resources engine aria2.conf"

经测试，如果安装路径不带空格，就不会出现此问题。
小白羊3.11.4没有此问题。

**Comment by WinXS** [comment]
同样报错

**Comment by grimwoo** [comment]
我碰到了同样的问题，请问三位可有什么好的解决方法？@cycloneblack @WinXS @gaozhangmin

**Comment by WinXS** [comment]
@grimwoo 我选择重新安装并选择名字没有空格的英文路径

**Comment by grimwoo** [comment]
@WinXS Thanks！
