### ISSUE TITLE
3.11.5版因安装路径有空格无限弹窗aria2c启动失败

### ISSUE THREAD

**Issue by huang95-Q** [gaozhangmin/aliyunpan#122]
Windows版最新3.115版小白羊安装路径有空格会导致aria2启动失败，然后系统无限弹窗提示

**Comment by 7noemo** [comment]
+1

**Comment by 7noemo** [comment]
![image](https://user-images.githubusercontent.com/103473489/233977594-e36a8e86-f0ea-42ad-984c-b7893176e0d4.png)
加载文件失败

**Comment by gaozhangmin** [comment]
等我申请到了账号一起解决

**Comment by fgr178707** [comment]
> ![image](https://user-images.githubusercontent.com/103473489/233977594-e36a8e86-f0ea-42ad-984c-b7893176e0d4.png) 加载文件失败

https://github.com/gaozhangmin/aliyunpan/discussions/133

**Comment by fgr178707** [comment]
> ![e203ada973a72710ee3c1fd5688975f](https://user-images.githubusercontent.com/54681896/234876819-b804dcbc-af22-469c-8c95-f3ba5f17660e.png)

#134

**Comment by Zhangxxl** [comment]
> Program Files把空格去掉。。。是不是作死？

微软故意的，不加引号是不规范的用法，通过Program Files空格要求开发者在路径上加上引号

**Comment by mchotdograp** [comment]
> 我只是反馈一下问题，解决方法早就知道了，不用你在这教
??????
我没有在教你啊 我是想到了这个办法但是觉得不靠谱啊
这么改的话这个文件夹下的其它应用不得出问题吗
