### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by qsxc369** [gaozhangmin/aliyunpan#13]
![image](https://user-images.githubusercontent.com/64853070/229506188-d02201de-f87d-44e0-8e4d-91c8eb53b570.png)
只能看到根目录，文件夹打不开

**Comment by gaozhangmin** [comment]
> ![image](https://user-images.githubusercontent.com/64853070/229506188-d02201de-f87d-44e0-8e4d-91c8eb53b570.png)
> 
> 只能看到根目录，文件夹打不开

把之前程序数据给清除掉。

**Comment by qsxc369** [comment]
已解决，谢谢大佬
