### ISSUE TITLE
列出文件夹失败

### ISSUE THREAD

**Issue by sakura-fly** [gaozhangmin/aliyunpan#131]
![图片](https://user-images.githubusercontent.com/24423214/235028547-987dee8e-76b0-4713-be15-ed2a79c2cc1a.png)

版本
3.11.5
系统
Ubuntu 20.04

**Comment by hangxj** [comment]
同情况

**Comment by zhtianmm11** [comment]
一样的问题，日志显示_FileListOnePage err=61efe83f2d912d11955846fead81e075a481f503 401

**Comment by shuai274** [comment]
我也是...

**Comment by j2eework** [comment]
列出文件夹失败 401

**Comment by onvz** [comment]
> ![图片](https://user-images.githubusercontent.com/24423214/235028547-987dee8e-76b0-4713-be15-ed2a79c2cc1a.png)
> 
> 版本 3.11.5 系统 Ubuntu 20.04

就是token的问题,参考这个,,注意,有两个的,
[https://github.com/gaozhangmin/aliyunpan/issues/114](url)

**Comment by shuai274** [comment]
> > ![图片](https://user-images.githubusercontent.com/24423214/235028547-987dee8e-76b0-4713-be15-ed2a79c2cc1a.png)
> > 版本 3.11.5 系统 Ubuntu 20.04
> 
> 就是token的问题，参考这个，，注意，有两个的， [https://github.com/gaozhangmin/aliyunpan/issues/114](url)

J就是按照这个来的 获取的access token列出文件夹失败

**Comment by onvz** [comment]
> > > ![图片](https://user-images.githubusercontent.com/24423214/235028547-987dee8e-76b0-4713-be15-ed2a79c2cc1a.png)
> > > 版本 3.11.5 系统 Ubuntu 20.04
> > 
> > 
> > 就是token的问题，参考这个，，注意，有两个的， [https://github.com/gaozhangmin/aliyunpan/issues/114](url)
> 
> J就是按照这个来的 获取的access token列出文件夹失败

看到说,3个小时之后就要重新获取一次,,

chrome,f12之后,,左下角点那个"code",右边就会出现  

access_token:"
expires_in:
refresh_token:"
token_type:

我之前没怎么留意就用了refresh_token ,就像你这样出现401,后来注意了,复制也很留意,,就正常了

**Comment by 16GR5-maoliyan** [comment]
版本
3.11.5
系统 win11 专业
一样错误。

**Comment by fgr178707** [comment]
> ![图片](https://user-images.githubusercontent.com/24423214/235028547-987dee8e-76b0-4713-be15-ed2a79c2cc1a.png)
> 
> 版本 3.11.5 系统 Ubuntu 20.04

access_token获取保姆级教程
https://github.com/gaozhangmin/aliyunpan/discussions/133

**Comment by fgr178707** [comment]
https://github.com/gaozhangmin/aliyunpan/discussions/133

**Comment by sadslince** [comment]
我一样用的access token 但是一样出现401错误

**Comment by fgr178707** [comment]
> 

那只能说明你操作有问题

**Comment by sadslince** [comment]
已经解决了
