### ISSUE TITLE
3.10.24修复版，可以自动刷新token

### ISSUE THREAD

**Issue by zlbwswws95** [gaozhangmin/aliyunpan#132]
[https://github.com/odomu/aliyunpan/releases/tag/v3.10.24](url)

**Comment by fgr178707** [comment]
兄弟，你发错了吧 
打开是
![image](https://user-images.githubusercontent.com/109357981/235284232-310508fb-6867-4c4a-a163-8ed556813a06.png)

**Comment by shuai274** [comment]
搞不懂，他咋自动刷新token啊？

**Comment by fgr178707** [comment]
> 搞不懂，他咋自动刷新token啊？

我也不明白呀 没看懂

**Comment by shuai274** [comment]
![33333333333333333333](https://user-images.githubusercontent.com/99074325/235285087-3bd041fa-adfc-4ce5-8d42-73ace897afe9.png)
这咋添加？？

**Comment by fgr178707** [comment]
> ![33333333333333333333](https://user-images.githubusercontent.com/99074325/235285087-3bd041fa-adfc-4ce5-8d42-73ace897afe9.png) 这咋添加？？

你这是用压缩包或者是安装包，麻烦发一下

**Comment by shuai274** [comment]
> > ![33333333333333333333](https://user-images.githubusercontent.com/99074325/235285087-3bd041fa-adfc-4ce5-8d42-73ace897afe9.png)这咋加加？？
> 
> 你这是用压缩包还是安装包，麻烦发一下

https://github.com/odomu/aliyunpan/releases/tag/v3.10.24

**Comment by fgr178707** [comment]
> > > ![33333333333333333333](https://user-images.githubusercontent.com/99074325/235285087-3bd041fa-adfc-4ce5-8d42-73ace897afe9.png)这咋加加？？
> > 
> > 
> > 你这是用压缩包还是安装包，麻烦发一下
> 
> https://github.com/odomu/aliyunpan/releases/tag/v3.10.24 这个

我给你个建议，你到这个链接上问问
https://github.com/odomu/aliyunpan/issues

**Comment by hangxj** [comment]
https://github.com/odomu/aliyunpan/releases

这个地址才对

**Comment by fgr178707** [comment]
> https://github.com/odomu/aliyunpan/releases
> 
> 这个地址才对

你们俩发的这个没区别

**Comment by zlbwswws95** [comment]
releases里的安装包被删了，必须到Actions里下载安装包，之后登录小白羊后，在设置里填写token,token值到Alist官网获取

**Comment by Andyqi0076** [comment]
至少3.10.24这个更新后，不用每次登录重新获取一次token了，设置不难，可以试试

**Comment by kratos9394** [comment]
又限速了，玩不起了又
