### ISSUE TITLE
spawn cmd.exe eacces 失败

### ISSUE THREAD

**Issue by hjonline** [gaozhangmin/aliyunpan#135]
安装最新3.11.5版，一启动跳出个窗口，标题是启动 aria2c 失败，窗口内容是 spawn c:\windows\system32\cmd.exe eacces 失败。

**Comment by fgr178707** [comment]
请发一下截图

> 安装最新3.11.5版，一启动跳出个窗口，标题是启动 aria2c 失败，窗口内容是 spawn c:\windows\system32\cmd.exe eacces 失败。

请发一下截图
