### ISSUE TITLE
不能登录账号

### ISSUE THREAD

**Issue by ji-zhaohui** [gaozhangmin/aliyunpan#14]
两次扫描二维码以后，（第二次二维码扫描显示登陆蜗牛云盘），不能进入云盘账户，始终显示“加载用户信息中”。
请帮忙检查

![image](https://user-images.githubusercontent.com/129757858/229516994-81bebf8d-0923-406f-99ea-026cc515257f.png)

**Comment by gaozhangmin** [comment]
> 两次扫描二维码以后，（第二次二维码扫描显示登陆蜗牛云盘），不能进入云盘账户，始终显示“加载用户信息中”。
> 
> 请帮忙检查
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/129757858/229516994-81bebf8d-0923-406f-99ea-026cc515257f.png)
> 
> 

多试几次 排除api的问题
