### ISSUE TITLE
预览窗口打不开文件

### ISSUE THREAD

**Issue by serein88** [gaozhangmin/aliyunpan#140]

**Comment by serein88** [comment]
![](https://s3.bmp.ovh/imgs/2023/05/05/765f2c8111c27f6c.png)
![](https://s3.bmp.ovh/imgs/2023/05/05/ac5ae9a30b905650.png)
![](https://s3.bmp.ovh/imgs/2023/05/05/706f3663fa8ca61e.png)
是我的操作哪里出问题了吗。扫码登陆，然后获取并输入token。预览窗口打不开视频、照片、文档，下载和上传没问题

**Comment by gaozhangmin** [comment]
首页有电报群，群里有最新版本，晚上会发布正式版本解决
