### ISSUE TITLE
请问下载时候 必须开启命令行监听16800才能下载如何解决 谢谢

### ISSUE THREAD

**Issue by 998137217749** [gaozhangmin/aliyunpan#142]
今天下了最新版然后运行后出现Aria2本地连接已断开问题，然后得开启下图右边的命令行窗口才能下载，一旦关闭，软件就不能下载了
<img width="1150" alt="截屏2023-05-05 23 57 10" src="https://user-images.githubusercontent.com/132691607/236508027-8e8d210c-52eb-4e0f-b6c6-2ac13194f66d.png">

**Comment by gaozhangmin** [comment]
你再试试新版本

**Comment by 998137217749** [comment]
> 你再试试新版本

您好 我下的就是3.11.5修复access_token登录问题 这个版本 但是为了解决aria2那个报错 只能运行那个监听窗口才行 要不就是安回原来老的版本
