### ISSUE TITLE
扫描一次二维码后提示”获取二维码出错，请退出小白羊重新运行“，请问我该如何解决呢

### ISSUE THREAD

**Issue by Jamie502** [gaozhangmin/aliyunpan#143]
![image](https://github.com/gaozhangmin/aliyunpan/assets/86527088/ff2edf44-f01d-409c-ad14-d12a1717b894)

**Comment by gaozhangmin** [comment]
这个版本不行了，用最新的版本

**Comment by yuhjifdu** [comment]
> 这个版本不行了，用最新的版本
最新版3.11.11版今天也这样，无法登陆
