### ISSUE TITLE
询问是否可以在qq建交流群？

### ISSUE THREAD

**Issue by AQ2706** [gaozhangmin/aliyunpan#144]
已看到作者建的电报群，但对一些不太会使用那些软件的人不太友好，所以想建个交流群，一些个人想法：
1.使用qq机器人创建自动回复，检测该关键词就会给出问题答案
2.可以在群文件放入官方版本，非官方版本（指修复版）听作者意见，可放可不放
3.在群公告放上最新版本号，修复了哪些问题
qq群号：821237761

**Comment by gaozhangmin** [comment]
我没有QQ。
