### ISSUE TITLE
感觉最新的这个版本有限速了,是最新的填入不同token导致的差异吗??

### ISSUE THREAD

**Issue by onvz** [gaozhangmin/aliyunpan#145]
之前的填入access token,和现在的填入refresh token 这两种方式,在aliyun那边看来是一样的吗?
还是说,这两种在aliyun那边会区别对待,就像超级管理员和普通用户的权限不一样那种,
家里是千兆,用之前的那个填入access token的客户端,,能拉爆家里的带宽虽然不能稳定保持一百多M每秒,但平均下来,八九十M每秒还是有的,
最新版的这个,全程都很稳定的保持在五十多M,大概就是一半带宽吧~~,

顺带问下, 为什么最新版的下载,不是在github了???? 跑到123云盘下载了

**Comment by gaozhangmin** [comment]
不会，token是一样的。只是获取token的方式不同。
