### ISSUE TITLE
下载的m3u8不合并

### ISSUE THREAD

**Issue by yhhdlcool** [gaozhangmin/aliyunpan#149]
如题，新版本的下载了m3u8

**Comment by gaozhangmin** [comment]
本地要下载ffmpeg，并在设置中指定路径

**Comment by lanzhous** [comment]
有ff但是还是不合并都是ts文件 怎么解决呐。

**Comment by gaozhangmin** [comment]
> 有ff但是还是不合并都是ts文件 怎么解决呐。
小白羊设置中指定路径了吗。并需要赋予可执行权限 chmod +x ffmpeg

**Comment by lanzhous** [comment]
chmod +x ffmpeg  cmd运行嘛?

**Comment by gaozhangmin** [comment]
> chmod +x ffmpeg cmd运行嘛?

对。设置中指定路径了吧，路径最好不要空格。

**Comment by 1049731887** [comment]
@gaozhangmin 该问题可以关闭了
