### ISSUE TITLE
aria2c 未知错误

### ISSUE THREAD

**Issue by dddaniel1** [gaozhangmin/aliyunpan#151]
下载文件就会出这个提示
![image](https://github.com/gaozhangmin/aliyunpan/assets/61337842/30cce980-1d9c-4d8a-9654-13dd7496a1d6)

**Comment by gaozhangmin** [comment]
怀疑是网络不太好，导致的超时断线，你可以看一下下载速度是否稳定（是一直保持1MB/s还是上下浮动非常剧烈）

仅从截图去分析

1.小白羊把下载任务推送给aria2
2.aria2去下载
3.小白羊刷新进度
现在是aria2下载过程中间出错了，
如果是每15-20分钟固定的时间失败一次/自动重试/固定间隔失败/自动重试/.... 说明时下载链接的问题
如果是下载中，下载速度剧烈波动，长时间速度为10kb/s以内，会因速度过低自动断开失败

**Comment by zpoyqx** [comment]
我也碰到了相同的问题，在校园网下会显示同样的错误，更换成手机热点就可以成功下载，不过校园网可以成功访问其他网页，不知道为什么会导致aria2c出错

**Comment by tasty007** [comment]
我也是出现这种情况, 上传和下载都不行, 只能换成官方APP

**Comment by Aluan1996** [comment]
同样的问题，换了好几个版本都是这样

**Comment by kindle939393** [comment]
> 怀疑是网络不太好，导致的超时断线，你可以看一下下载速度是否稳定（是一直保持1MB/s还是上下浮动非常呼吸）
> 
> 只需从截图去分析
> 
> 1.小白羊把下载任务主动给aria2 2.aria2下载 3.小白羊刷新进度 现在是aria2下载过程中间出错了， 如果是每15-20分钟固定的时间失败一次/自动重试/固定间隔失败/自动重试/.... 说明时下载链接的问题 如果是下载中，下载速度同步震动，时长速度为10kb/s以内，会因速度过低断开自动失败

我没有设置aira2，它也跟我说这个aira2错误。我用的是小白羊下载还是这样
