### ISSUE TITLE
输入refresh_token后正在跳转一直转圈

### ISSUE THREAD

**Issue by Theodore-98** [gaozhangmin/aliyunpan#153]

**Comment by gaozhangmin** [comment]
多试几次呢。

**Comment by autumndays** [comment]
> 多试几次呢。

同样转圈，运行日志显示错误信息：
HttpError4 status=400 code=Invalid request message=Request failed with status code 400

**Comment by missuo** [comment]
一样的问题。

**Comment by missuo** [comment]
@Theodore-98 解决了，应该是阿里云盘登陆的设备不能超过5个，你可以在手机端App删除几个登录的设备之后，尝试重新填写refresh_token登录。

**Comment by Theodore-98** [comment]
> @Theodore-98 解决了，应该是阿里云盘登陆的设备不能超过5个，你可以在手机端App删除几个登录的设备之后，尝试重新填写refresh_token登录。

手机端显示可登录10个设备，我只登录了三个，回头再试试

**Comment by autumndays** [comment]
> @Theodore-98 解决了，应该是阿里云盘登陆的设备不能超过5个，你可以在手机端App删除几个登录的设备之后，尝试重新填写refresh_token登录。

无解 日志里还是报错400

**Comment by gaozhangmin** [comment]
下个版本 就不用手动获取token了。
