### ISSUE TITLE
Refresh_token 获取

### ISSUE THREAD

**Issue by gaozhangmin** [gaozhangmin/aliyunpan#155]
❗  暂时没申请到阿里云盘Open平台账号，临时方案需要自己手动获取Refresh Token，用于获取access_token。

1. 访问https://alist.nn.ci/tool/aliyundrive/request.html

![image](https://user-images.githubusercontent.com/9278488/236428549-5869fb82-cd0f-41a1-bb58-decd264b3c4e.png)

2. 点击Scan QrCode，使用阿里云盘APP，扫描二维码，授权访问

3. 扫码后，点击“I have scan”按钮，获取对应refresh token。录入小白羊APP。

![image](https://user-images.githubusercontent.com/9278488/236429004-3d21b19f-d205-4260-9399-cbaf9fbfc00d.png)

**Comment by zcmi** [comment]
怎么录入？找半天没找到路口
![图片](https://github.com/gaozhangmin/aliyunpan/assets/24654015/f0a95ff7-24af-482e-9930-9e485d2396ca)
