### ISSUE TITLE
aria2

### ISSUE THREAD

**Issue by CanonLs** [gaozhangmin/aliyunpan#156]
版本：小白羊3.11.6
MacOS版本：12.6.6
aria2c路径：/usr/local/Cellar/aria2/1.36.0/bin/aria2c
配置文件路径：/Users/canonls/.aria2/aria2.conf
### **配置文件代码**
`dir=~/Downloads
disk-cache=32M
continue=true
max-concurrent-downloads=32
max-connection-per-server=16
min-split-size=10M
split=32
max-overall-upload-limit=5M
disable-ipv6=false
input-file=.aria2/aria2.session
save-session=.aria2/aria2.session
save-session-interval=60
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-listen-port=16800
rpc-secret=1
follow-torrent=true
listen-port=51413
enable-dht=true
enable-dht6=true
bt-enable-lpd=true
enable-peer-exchange=true
peer-id-prefix=-TR2770-
user-agent=Transmission/2.77
seed-ratio=2.0
force-save=false
bt-seed-unverified=true`

**具体表现**
可以正常下载，但是没有进度反馈，下载完成没有反馈，下载完成后文件追加后缀‘.td’ ,下载过程中频繁aria2报错 
**日志如图**
![WX20230517-051112](https://github.com/gaozhangmin/aliyunpan/assets/23548112/d9536bd0-77c1-4fed-bbc4-2580073abfee)
麻烦看一下是什么问题呗

**Comment by gaozhangmin** [comment]
你是在设置中自己指定aria2c 路径和配置文件，启动的吗？ @CanonLs

**Comment by CanonLs** [comment]
> 你在设置中自己指定aria2c路径和配置文件，启动的吗？@CanonLs

刚下载小白羊之后 下载大型文件提示aria2c 错误 无法创建文件夹 然后我就自行安装了aria 添加好路径和配置路径  然后重启打开小白羊 就看到了各种报错

**Comment by gaozhangmin** [comment]
你再试试3.11.7

**Comment by zpoyqx** [comment]
我在不手动指定aria2c的情况下，直接下载最新版(3.11.7)的小白羊也会碰到一样的aria2c未知错误

**Comment by myworksfun** [comment]
![Snipaste_2023-05-27_09-18-32](https://github.com/gaozhangmin/aliyunpan/assets/45185967/96b54790-2779-4e71-a032-09da765eb13a)
## aria2cz同样的一直报错。
