### ISSUE TITLE
MacOs无法下载！x

### ISSUE THREAD

**Issue by luoguanping** [gaozhangmin/aliyunpan#16]

**Comment by luoguanping** [comment]
Aria2本地连接已断开

**Comment by gaozhangmin** [comment]
> Aria2本地连接已断开

自己用命令行在本地尝试起下。

aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800

**Comment by Misaka-9982-coder** [comment]
> > Aria2本地连接已断开
> 
> 自己用命令行在本地尝试起下。
> 
> aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800

使用了命令行后，报错如下：

![image](https://user-images.githubusercontent.com/63705582/229745705-bbec3f87-eaa9-4f1f-b2ef-026d97b98bf6.png)

**Comment by conan4803** [comment]
aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800
zsh: command not found: aria2c
请问是要单独安装aria2服务还是要在特定目录下运行呢？

**Comment by gaozhangmin** [comment]
> aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800
> 
> zsh: command not found: aria2c
> 
> 请问是要单独安装aria2服务还是要在特定目录下运行呢？

建议直接本地安装一个。

**Comment by conan4803** [comment]
> 您好，安装了aria2，然后运行了aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800
没有报错，但是app运行还是报错，如图

![CleanShot 2023-04-04 at 19 58 34@2x](https://user-images.githubusercontent.com/3960732/229784812-14459fe8-55dd-4aa6-a487-f9f722ccb979.png)
