### ISSUE TITLE
上传文件夹时会额外上传空文件夹

### ISSUE THREAD

**Issue by zpoyqx** [gaozhangmin/aliyunpan#162]
将文件夹上传时，会生成文件夹下的目录的路径命名的空文件夹，想询问该如何解决
![Snipaste_2023-05-20_15-13-38](https://github.com/gaozhangmin/aliyunpan/assets/56358596/f000a1ef-4b44-49bb-af2b-c840c89849f7)

**Comment by gaozhangmin** [comment]
你用的那个版本？我本地在windows 和 mac都验证过这个修复，都没问题的。

**Comment by zpoyqx** [comment]
我用的是最新的版本3.11.7，是不是哪里的设置有问题呢？

**Comment by gaozhangmin** [comment]
这个我测试了很多次，无法复现

**Comment by huangz986** [comment]
一样版本，windows，确认有这个问题。
