### ISSUE TITLE
感谢开发分享，请问后续能否考虑增加音轨切换功能？

### ISSUE THREAD

**Issue by elitever** [gaozhangmin/aliyunpan#164]
小白羊能否增加音轨切换，因为不少中英文电影想切换到国语观看，所以期待增加该功能，之前的小白羊用MPV播放器时就可以切换音轨。

**Comment by zlbwswws95** [comment]
> 这个切换音轨 需要网盘内有对应的音轨资源吧？

他应该是希望当视频内置多个音轨时，小白羊内置的播放器可以像potplayer一样切换音轨

**Comment by gaozhangmin** [comment]
目前用的这个artplayer不支持多音轨。

**Comment by jlu511** [comment]
> 目前用的这个artplayer不支持多音轨。

能否调用本地播放器的时候，支持网盘内同名字幕加载？目前，自带artplayer，可以实现网盘内同名字幕加载，但是不能切换音轨。而使用自定义本地播放器，如MPV等，又无法网盘内同名字幕加载。

**Comment by gaozhangmin** [comment]
> > 目前用的这个artplayer不支持多音轨。
> 
> 
> 
> 能否调用本地播放器的时候，支持网盘内同名字幕加载？目前，自带artplayer，可以实现网盘内同名字幕加载，但是不能切换音轨。而使用自定义本地播放器，如MPV等，又无法网盘内同名字幕加载。
> 
> 

这个下个版本会支持
