### ISSUE TITLE
一个小需求，左侧显示文件夹树结构，右侧只显示文件夹内文件不显示子文件夹（根目录也只显示文件）？

### ISSUE THREAD

**Issue by Yamazaki-wu** [gaozhangmin/aliyunpan#165]
左侧显示文件夹树结构，右侧只显示文件夹内文件不显示子文件夹（根目录也只显示文件）？
作者能否愿意添加这样一个功能选项（不知是否说明清楚了）？
另外，彻底删除功能是否可以做到右键菜单中？菜单栏中最好能上调一级，而不是“彻底删除——删除后无法还原”

**Comment by gaozhangmin** [comment]
第一个修改没有充分理由 不做。 
第2个可以做
