### ISSUE TITLE
登录此app需要扫两次二维码，第二次好像是授权Alist，开发者大佬是否自己搞了个nas？

### ISSUE THREAD

**Issue by YEW151** [gaozhangmin/aliyunpan#166]
如题，想知道第二次授权是什么？是否是一个nas？

**Comment by shemengjia** [comment]
第二个二维码用阿里云盘扫不起来啥情况

**Comment by YEW151** [comment]
> 第二个二维码用阿里云盘扫不起什么情况

可以扫，点下面的跳转链接会出现一个大的二维码就可以扫了，但是在开发者没作说明前不建议扫，因为那啥授权Alist的，相当于是授权自己的网盘挂载到服务器或者本地上，而这个挂载方咱们是没有任何控制权......

**Comment by YEW151** [comment]
> 第二个二维码用阿里云盘扫不起什么情况

授权挂载，但对挂载的服务器也好或者本地也好我们没有任何控制权，但部署Alist的一方却有对网盘的控制权，一个是隐私泄露的风险还有一个是文件丢失的风险，这玩意儿就是个第三方网盘管理器。原版好像不用二次扫码的吧？

**Comment by gaozhangmin** [comment]
不是 我只是把alist网页嵌入了进来。

**Comment by YEW151** [comment]
> 不是 我只是把alist网页嵌入了进来。

懂了，这么做是更好的获取token？

**Comment by YEW151** [comment]
> 不是 我只是把alist网页嵌入了进来。

只是方便管理，并没有在云上，而是在本地部署对吧

**Comment by gaozhangmin** [comment]
> > 不是 我只是把alist网页嵌入了进来。
> 
> 
> 
> 懂了，这么做是更好的获取token？

对 跟alist挂载无关。只是为了方便获取token

**Comment by YEW151** [comment]
> > > 不是 我只是把alist网页嵌入了进来。
> > 
> > 
> > 懂了，这么做是更好的获取token？
> 
> 对 跟alist挂载无关。只是为了方便获取token

那请问相关路径是什么？二维码生成文件的本地路径
