### ISSUE TITLE
3.11.8  在线播放限速  卡爆了！！

### ISSUE THREAD

**Issue by wsjmxz** [gaozhangmin/aliyunpan#171]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.8  

### 系统 System

WIN

### 复现步骤 Reproduce step

3.11.8  在线播放限速  卡爆了！！

### 你看到了什么错误？What errors do you see?

3.11.8  在线播放限速  卡爆了！！

### 你期望看到什么？What did you expect to see?

1

### 还有其他的内容吗？Anything else?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
你指的卡是打开视频前加载慢，还是播放卡顿？

**Comment by dai022** [comment]
比如在potplayer之前加载速度10m/s，现在只有90kb/s了

**Comment by dai022** [comment]
> 你指的卡是打开视频前加载慢，还是播放卡顿？



> 你指的卡是打开视频前加载慢，还是播放卡顿？

potplayer之前加载速度10m/s，现在只有90kb/s

**Comment by dai022** [comment]
potplayer之前加载速度10m/s，现在只有90kb/s

**Comment by wsjmxz** [comment]
> 你指的卡是打开视频前加载慢，还是播放卡顿？

在线播放视频卡顿，3.11.7不存在这个问题，升级3.11.8后在线播放视频卡顿，而且删除3.11.8后安装回3.11.7一切正常，但是3.11.7关闭一次自动更新到3.11.8。

**Comment by wsjmxz** [comment]
> potplayer之前加载速度10m/s，现在只有90kb/s

别去更新3.11.8，我手贱，现在只能每次用的时候用3.11.7安装包，用一次后它自动更新到3.11.8

**Comment by gaozhangmin** [comment]
因为外部视频播放支持了加载字幕和播放列表的关系。所以加载会比以前慢点。而且3.11.7没有自动更新的功能。需要自己下载重新安装。源码都在仓库里。 @wsjmxz @dai022

**Comment by gaozhangmin** [comment]
可以在设置里关掉时加载字幕和跳转历史进度。
