### ISSUE TITLE
[Bug] 海外ISP无法加载第二个登录二维码

### ISSUE THREAD

**Issue by 1360576570** [gaozhangmin/aliyunpan#172]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.8.0

### 系统 System

Windows 7 64 bit Ultimate Edition Service Pack 1

### 复现步骤 Reproduce step

1. 解压后第一次运行时登录我的小号，此时可以正常登录，可以调用PotPlayer播放视频。
2. 用我的大号尝试登录，但登录成功后无法正常播放视频，发现下载速度在100KB/s以下。
3. 以为是出bug了，遂清除软件缓存并尝试重新登录小号。

### 你看到了什么错误？What errors do you see?

清除软件缓存后尝试登录小号，发现第一个二维码可以正常显示，第二个无法显示，提示“获取二维码出错，请退出小白羊后重新运行”。重新解压运行，清除软件缓存，重启计算机，用其他未登录过的账号登录，均无法消除这一bug，使第二个二维码正常显示。

### 你期望看到什么？What did you expect to see?

更换其他小白羊客户端，登录二维码可以正常显示，可以正常登录。

### 还有其他的内容吗？Anything else?

IP是干净的，为海外家用宽带。手机访问阿里系APP（淘宝支付宝等），电脑访问其他国内网页，均未发现无法加载的问题。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by 1360576570** [comment]
发现运行日志里有如下错误：
ApiTokenRefreshAccount err=200

**Comment by gaozhangmin** [comment]
这是调用获取token接口被限流了， 换个ip。 @1360576570  
等下会发布3.11.9 紧急修复下外部播放器卡顿bug。

**Comment by 1360576570** [comment]
谢谢。向ISP申请更换IP地址后，大小号均成功登录，大号仍旧无法正常播放视频，小号正常使用。想切回大号时，软件提示需要重新登录，尝试重新登录时问题复现，现在大小号均无法登录。
难道阿里云盘也有“黑号”一说？

**Comment by gaozhangmin** [comment]
你等下下载3.11.9 试下。 @1360576570

**Comment by gaozhangmin** [comment]
试下3.11.9

**Comment by 1360576570** [comment]
好的，我下载一个试试，有问题的话再反馈。

**Comment by 1360576570** [comment]
新版本一切正常。大号也没有限速问题了，感谢大佬！

另外汇报一个小bug：设置选项里的开关图标UI略有错位，不知道是不是因为和Windows 7系统的兼容问题。
![Image 020](https://github.com/gaozhangmin/aliyunpan/assets/47458261/2a9d794f-ff24-4b86-9a7c-d8631bedae9e)

**Comment by gaozhangmin** [comment]
> 新版本一切正常。大号也没有限速问题了，感谢大佬！
> 
> 
> 
> 另外汇报一个小bug：设置选项里的开关图标UI略有错位，不知道是不是因为和Windows 7系统的兼容问题。
> 
> ![Image 020](https://github.com/gaozhangmin/aliyunpan/assets/47458261/2a9d794f-ff24-4b86-9a7c-d8631bedae9e)

帮忙点个star

**Comment by 1360576570** [comment]
好嘞，谢谢大佬。阿里云WebDAV结束支持华硕ARM380梅林改版固件支持后，就靠你的软件调用PotPlayer访问阿里云盘的影音资源了。
