### ISSUE TITLE
无法修改缓存目录

### ISSUE THREAD

**Issue by 454592673** [gaozhangmin/aliyunpan#173]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

无法修改缓存目录

### 描述 Motivation

![image](https://github.com/gaozhangmin/aliyunpan/assets/22283930/21b39f74-8aa7-423a-b78b-ae5806d14ba3)
想把软件下载缓存目录换成ramdisk内存盘，但是配置里面只能看，不能改
idm配置内存盘作缓存，实测可以满速下载
![image](https://github.com/gaozhangmin/aliyunpan/assets/22283930/d1a67095-2810-4d3f-b37f-af72c1e191f8)

### Solution

能否修改缓存目录

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by 454592673** [comment]
想了解小白羊多线程下载是和idm一样根据线程拆分下载成多个文件最后合并，还是和迅雷那种，先预划一个整体磁盘空间再下载的

**Comment by gaozhangmin** [comment]
下个版本加这个功能。
