### ISSUE TITLE
3.11.8版本调用第三方播放器速度特别慢[Bug] {{请输入标题，不要留空 - Please enter a title, do not leave it blank.}}

### ISSUE THREAD

**Issue by 6su6** [gaozhangmin/aliyunpan#174]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.8

### 系统 System

win

### 复现步骤 Reproduce step

调用第三方播放器时，加载速度只有100kb左右，用内置播放器速度正常

### 你看到了什么错误？What errors do you see?

速度慢

### 你期望看到什么？What did you expect to see?

被修复

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
等下修复。

**Comment by gaozhangmin** [comment]
去试试11.9吧。@6su6

**Comment by 6su6** [comment]
原来的放映室怎么变样了，只有文件夹了，没有之前那样的不好找了😭
