### ISSUE TITLE
[Bug] 无法加载相册

### ISSUE THREAD

**Issue by DukeFox** [gaozhangmin/aliyunpan#175]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.9

### 系统 System

Win 11

### 复现步骤 Reproduce step

新安装后，扫两次码登录后就显示这个错误，相册无法显示。

### 你看到了什么错误？What errors do you see?

29 23:54:07 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'thumbnail') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'thumbnail')
    at file:///C:/Users/Duke/AppData/Local/Programs/xbyyunpan/resources/app.asar/dist/index.js:195:94304
    at Array.forEach (<anonymous>)
    at AliAlbum.ApiAlbumsList (file:///C:/Users/Duke/AppData/Local/Programs/xbyyunpan/resources/app.asar/dist/index.js:195:94181)
    at async Proxy.getAlbumList (file:///C:/Users/Duke/AppData/Local/Programs/xbyyun...
29 23:53:44 : success : 小白羊启动

### 你期望看到什么？What did you expect to see?

新安装后，扫两次码登录后就显示这个错误，相册无法显示。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
你相册怎么都没有封面

**Comment by gaozhangmin** [comment]
@DukeFox  https://www.123pan.com/s/wbncVv-IObcv.html 你试下这个版本。

**Comment by shemengjia** [comment]
> 你相册怎么都没有封面

一样的，我才更新了3.11.9，图库和我的相册都没得，一片白
![QQ截图20230530125643](https://github.com/gaozhangmin/aliyunpan/assets/32380465/6ed8ac08-f07f-4ec6-9681-b036f7c1aa39)

**Comment by gaozhangmin** [comment]
你下我提供的那个临时版本

**Comment by gaozhangmin** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/9278488/ae2ad8b0-21b3-49ca-8eef-fbcb35083bf8)

@DukeFox 试过了吗？

**Comment by DukeFox** [comment]
> @DukeFox https://www.123pan.com/s/wbncVv-IObcv.html 你试下这个版本。

这个版本可以用了，没有报错，且相册正常显示了。
