### ISSUE TITLE
[Bug] {{小白羊自动更新弹窗错误 - Please enter a title, do not leave it blank.}}

### ISSUE THREAD

**Issue by shemengjia** [gaozhangmin/aliyunpan#176]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.8

### 系统 System

win11

### 复现步骤 Reproduce step

3.11.8打开提示更新，然后在更新下载好安装包后安装的时候弹出这个界面

### 你看到了什么错误？What errors do you see?

![QQ截图20230530125156](https://github.com/gaozhangmin/aliyunpan/assets/32380465/09fc32af-9b98-4061-aa91-43eff04392bf)

### 你期望看到什么？What did you expect to see?

1

### 还有其他的内容吗？Anything else?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
管理员权限运行
