### ISSUE TITLE
求增加显示视频时长和视频分辨率的功能

### ISSUE THREAD

**Issue by abcde696969** [gaozhangmin/aliyunpan#177]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

求增加显示视频时长和视频分辨率的功能

### 描述 Motivation

在每个视频的旁边，增加显示视频时长和视频分辨率的功能

### Solution

在每个视频的旁边，增加显示视频时长和视频分辨率的功能

### 还有其他内容吗？Anything else?

在每个视频的旁边，增加显示视频时长和视频分辨率的功能

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
视频时长不是进度条能看到吗？分辨率 你选择视频分辨率也能看到

**Comment by abcde696969** [comment]
开发大大说的操作是可行的，但是需要鼠标右击某个视频，弹出菜单里，选择：更多，再选择“属性”。能不能直接把视频时长、分辨率这2个属性，直接添加到对应的视频右侧最后一列进行显示。

**Comment by gaozhangmin** [comment]
截图 说清楚加在哪。我看下合理不合理

**Comment by abcde696969** [comment]
加在红色区域这个地方
![123](https://github.com/gaozhangmin/aliyunpan/assets/133623007/0687f606-aea1-465c-99ee-1504d54789f9)

**Comment by gaozhangmin** [comment]
> 加在红色区域这个地方
> 
> ![123](https://github.com/gaozhangmin/aliyunpan/assets/133623007/0687f606-aea1-465c-99ee-1504d54789f9)
> 
> 

这个不能做。会影响文件树的加载速度。

**Comment by shemengjia** [comment]
> 截图 说清楚加在哪。我看下合理不合理

老哥现在3.11.9单机文件咋弹出“选出一个文件选出一个位置”这个提示的窗口啊，关闭后才是播放视频
![image](https://github.com/gaozhangmin/aliyunpan/assets/32380465/81b5c748-fc0b-4c70-8333-23a34cf646d4)

**Comment by shemengjia** [comment]
> > > 截图 说清楚加在哪。我看下合理不合理
> > 
> > 
> > 老哥现在3.11.9单机文件咋弹出“选出一个文件选出一个位置”这个提示的窗口啊，关闭后才是播放视频
> > ![image](https://user-images.githubusercontent.com/32380465/241944391-81b5c748-fc0b-4c70-8333-23a34cf646d4.png)
> 
> 啥意思？点击播放视频会跳出这个吗？

对的，然后关闭了这个窗口才会播放视频，很奇怪

**Comment by shemengjia** [comment]
> > > 截图 说清楚加在哪。我看下合理不合理
> > 
> > 
> > 老哥现在3.11.9单机文件咋弹出“选出一个文件选出一个位置”这个提示的窗口啊，关闭后才是播放视频
> > ![image](https://user-images.githubusercontent.com/32380465/241944391-81b5c748-fc0b-4c70-8333-23a34cf646d4.png)
> 
> 啥意思？点击播放视频会跳出这个吗？


> > > 截图 说清楚加在哪。我看下合理不合理
> > 
> > 
> > 老哥现在3.11.9单机文件咋弹出“选出一个文件选出一个位置”这个提示的窗口啊，关闭后才是播放视频
> > ![image](https://user-images.githubusercontent.com/32380465/241944391-81b5c748-fc0b-4c70-8333-23a34cf646d4.png)
> 
> 啥意思？点击播放视频会跳出这个吗？

点击视频文件弹出这个窗口，点击ZIP这种压缩文件会在线浏览已解压的文件

**Comment by gaozhangmin** [comment]
> 加在红色区域这个地方 ![123](https://user-images.githubusercontent.com/133623007/241898687-0687f606-aea1-465c-99ee-1504d54789f9.jpg)

这个之前是支持的，旧版接口里返回了视频时长和分辨率数据，但是新版api没有这些数据了。

**Comment by abcde696969** [comment]
> > 加在红色区域这个地方 ![123](https://user-images.githubusercontent.com/133623007/241898687-0687f606-aea1-465c-99ee-1504d54789f9.jpg)
> 
> 这个之前是支持的，旧版接口里返回了视频时长和分辨率数据，但是新版api没有这些数据了。

如果新版api没有这些数据了，但是在鼠标右击某个视频，弹出菜单里，选择：更多，再选择“属性”里面，却有这些数据啊

**Comment by gaozhangmin** [comment]
> > > 加在红色区域这个地方 ![123](https://user-images.githubusercontent.com/133623007/241898687-0687f606-aea1-465c-99ee-1504d54789f9.jpg)
> 
> > 
> 
> > 这个之前是支持的，旧版接口里返回了视频时长和分辨率数据，但是新版api没有这些数据了。
> 
> 
> 
> 如果新版api没有这些数据了，但是在鼠标右击某个视频，弹出菜单里，选择：更多，再选择“属性”里面，却有这些数据啊

那是额外请求其他api返回的。不能在列举文件树时候去为每一个视频文件额外请求一个api，我测试了。会导致文件树加载时长不可接受。
