### ISSUE TITLE
[Bug] {{登陆的时候下面的提示把二维码挡住了，扫不出来}}

### ISSUE THREAD

**Issue by taswsz** [gaozhangmin/aliyunpan#179]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.9

### 系统 System

windows11 pro 22621.1702

### 复现步骤 Reproduce step

在输入密码或者扫码后，会弹出alist授权的二维码，这时候下面有行提示把二维码下面一小部分挡住了。必须手机一直对着屏幕，在app上同意后立马再打开扫码才可以。下面提示里的链接也拉不起浏览器来，也无法复制

### 你看到了什么错误？What errors do you see?

在输入密码或者扫码后，会弹出alist授权的二维码，这时候下面有行提示把二维码下面一小部分挡住了。必须手机一直对着屏幕，在app上同意后立马再打开扫码才可以。

### 你期望看到什么？What did you expect to see?

none

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
不会吧 
要不然登录不了 很多人会来反馈的

**Comment by gaozhangmin** [comment]
我稍微把二维码往上提提
