### ISSUE TITLE
[Bug] {{登录后界面上一直显示“加载用户信息中，但貌似并不影响使用”}}

### ISSUE THREAD

**Issue by Yamazaki-wu** [gaozhangmin/aliyunpan#180]
### Please search before asking

- [ ] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [ ] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.9

### 系统 System

win10 22h2

### 复现步骤 Reproduce step

打开软件，在下方就有提示。

![Clipboard 1](https://github.com/gaozhangmin/aliyunpan/assets/13083879/d65e3ffb-c7ca-4597-8c09-f97a61622cc4)

### 你看到了什么错误？What errors do you see?

提示：加载用户信息中

### 你期望看到什么？What did you expect to see?

没有此提示，或者提示一下就消失了。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by wsjmxz** [comment]
> > 是的我也这样
> 
> 清理下载存储。重新打开软件。

清理了，还是不能登陆。 扫码后一直转圈圈。3.11.10也是这样。今晚上发现的。
