### ISSUE TITLE
[Bug] {{登录的时候弹窗提示错误信息，并无法读取根目录文件}}

### ISSUE THREAD

**Issue by shaoclouds** [gaozhangmin/aliyunpan#181]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.9

### 系统 System

win10 1809

### 复现步骤 Reproduce step

直接打开登录

### 你看到了什么错误？What errors do you see?

![image](https://github.com/gaozhangmin/aliyunpan/assets/83697448/69eca732-b013-4ec1-b5b4-ab5c12e76bad)

### 你期望看到什么？What did you expect to see?

正常读取目录文件

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@shaoclouds 设置中清理下缓存。这个我后面会修复

**Comment by Cribug666** [comment]
大佬，电报群莫名消失了，能再发一下邀请链接吗？
