### ISSUE TITLE
[Bug] {{检测、自动更新失败}}

### ISSUE THREAD

**Issue by xiaowulang-turbo** [gaozhangmin/aliyunpan#185]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.9

### 系统 System

win10 2019ltsc

### 复现步骤 Reproduce step

点击设置里的“检测更新”。

### 你看到了什么错误？What errors do you see?

![image](https://github.com/gaozhangmin/aliyunpan/assets/93776841/c08ea625-8a55-413a-9b3d-7e79969898ba)
显示你的本地版本3.11.9高于服务器版本3.11.10。

### 你期望看到什么？What did you expect to see?

期望自动下载更新并静默覆盖安装。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
3.11.11解决了
