### ISSUE TITLE
[Bug] {{更新后用户数据丢失.}}

### ISSUE THREAD

**Issue by xiaowulang-turbo** [gaozhangmin/aliyunpan#187]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.10

### 系统 System

win10 2019ltsc

### 复现步骤 Reproduce step

从3.11.9更新到3.11.10后（覆盖安装，不过安装时原小白羊尚在运行，提示退出后继续安装），不清楚其他版本更新是否有此问题。

### 你看到了什么错误？What errors do you see?

用户数据丢失，需要重新登录。

### 你期望看到什么？What did you expect to see?

期望保留原有token。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
解决了
