### ISSUE TITLE
[Bug] {{请输入标题，不要留空 - Please enter a title, do not leave it blank.}}

### ISSUE THREAD

**Issue by xingsuxingchen** [gaozhangmin/aliyunpan#189]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.11

### 系统 System

windows10-1909

### 复现步骤 Reproduce step

potplayer

### 你看到了什么错误？What errors do you see?

自定义播放器加载播放要等待20秒以上

### 你期望看到什么？What did you expect to see?

5-10s以内加载速度

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by bluearpy** [comment]
我没问题啊

**Comment by xingsuxingchen** [comment]
可能设置好后需要重新打开会好些
