### ISSUE TITLE
[Bug] deb 包安装报错

### ISSUE THREAD

**Issue by atzlinux** [gaozhangmin/aliyunpan#190]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.11

### 系统 System

Debian 11 atzlinux 11.7 amd64

### 复现步骤 Reproduce step

在安装 XBYDriver-3.11.11-linux-amd64.deb 软件包时，可以重复出现

### 你看到了什么错误？What errors do you see?

 apt install ./XBYDriver-3.11.11-linux-amd64.deb 

正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
注意，选中 'xbyyunpan' 而非 './XBYDriver-3.11.11-linux-amd64.deb'
下列【新】软件包将被安装：
  xbyyunpan
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
需要下载 0 B/68.4 MB 的归档。
解压缩后会消耗 242 MB 的额外空间。
获取:1 /home/atzlinux/下载/XBYDriver-3.11.11-linux-amd64.deb xbyyunpan amd64 3.11.11 [68.4 MB]
(正在读取数据库 ... 系统当前共安装有 203757 个文件和目录。)
准备解压 .../XBYDriver-3.11.11-linux-amd64.deb  ...
正在解压 xbyyunpan (3.11.11) ...
dpkg: 处理归档 /home/atzlinux/下载/XBYDriver-3.11.11-linux-amd64.deb (--unpack)时出错：
 新建硬链接 ./opt/小白羊云盘/resources/images/icon.png 时出错: 无效的跨设备链接
dpkg-deb: 错误: 粘贴 子进程被信号(断开的管道) 终止了
在处理时有错误发生：
 /home/atzlinux/下载/XBYDriver-3.11.11-linux-amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

### 你期望看到什么？What did you expect to see?

deb 包能够正常安装完成

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by atzlinux** [comment]
新建硬链接 ./opt/小白羊云盘/resources/images/icon.png 时出错: 无效的跨设备链接

我电脑上的 opt 目录，是使用的一个单独的分区，但安装其它软件包都没有出现这个问题。

不知道是不是这个 icon.png 文件是否有问题？

**Comment by atzlinux** [comment]
hrw-r--r-- 0/0               0 2023-06-03 11:49 ./opt/\345\260\217\347\231\275\347\276\212\344\272\221\347\233\230/resources/images/icon.png link to ./usr/share/icons/hicolor/0x0/apps/xbyyunpan.png

把 deb 包解开，看了下， tar tJvf data.tar.xz

是错误的把这个文件，作为符号链接打包了，而目标文件又不存在，所以导致安装报错。

**Comment by gaozhangmin** [comment]
@atzlinux  谢谢 我看下
