### ISSUE TITLE
[Bug] 自动更新报错

### ISSUE THREAD

**Issue by Aurora-20** [gaozhangmin/aliyunpan#191]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.11

### 系统 System

Windows

### 复现步骤 Reproduce step

1. 自动更新文件的下载路径是`.\resources\`，软件安装逻辑是先删除`.\`下所有文件，再重新运行安装包。
2. 然后从github下载完成后，进行全量更新的时候就会一直报错（具体的报错窗口忘了示截图了）。
3. 解决方法：给下载的全量包换一个位置。

### 你看到了什么错误？What errors do you see?

忘了截图了

### 你期望看到什么？What did you expect to see?

可以直接全量更新

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Aurora-20** [comment]
是从3.11.10更新到3.11.11时出现的问题，不知道3.11.11是否已经解决（因为没有3.11.12）

**Comment by gaozhangmin** [comment]
确实是这样，下个版本修复
