### ISSUE TITLE
[Bug] {{如图：雪碧图文字显示换行；文件和文件夹大小显示为整数，如2.xxG显示2G}}

### ISSUE THREAD

**Issue by 236507** [gaozhangmin/aliyunpan#192]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.11

### 系统 System

win8

### 复现步骤 Reproduce step

![image](https://github.com/gaozhangmin/aliyunpan/assets/93651002/a80aee2d-b338-42bd-9990-a70e8366f61d)

### 你看到了什么错误？What errors do you see?

左侧的文字，3三个汉字就换行：
如“**文件大小**：”显示为
**文件大
小：**

### 你期望看到什么？What did you expect to see?

不换行；

### 还有其他的内容吗？Anything else?

另文件大小希望显示小数位

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
OK 下个版本修复
