### ISSUE TITLE
[Bug] {{3.11.11版的下载速度还是跑不满宽带,但是旧版的3.11.5版就可以}}

### ISSUE THREAD

**Issue by onvz** [gaozhangmin/aliyunpan#194]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.5

### 系统 System

win10

### 复现步骤 Reproduce step

安装最新的3.11.11版,然后下载大文件,11G左右,速度大概是在20M-40多m /s,最高,大概是到500兆的样子

然后停止,删除文件,  用3.11.5版下载同样一个大文件,速度可以拉爆我的宽带,千兆,,基本可以保持在七八十m/s,,时不时会飙到100多m/s,,

### 你看到了什么错误？What errors do you see?

两个版本的下载速度不一样

### 你期望看到什么？What did you expect to see?

理论上,都是在阿里云盘下载同一个文件,而且用的账号都是一样的,应该速度一样才对,,但是差距有点大,

### 还有其他的内容吗？Anything else?

3.11.5这个版本是,需要手动输入access_token的,相隔几个小时之后就要手动输入
最新版的看说明,貌似不用了,而且听到说,新版的token的问题,两个版本理论是一样的

可是,就是不明白为什么两个版本的下载速度相差这么多,,是什么问题,有大佬可以搞明白吗?

其实,最终就是希望,可以像新版那样,不用每次输入token,而且又可以有3.11.5版那样的下载速度,

用过的都知道,速度快起来真的很爽,十几几十G的电影,嗖一声就下载完了,,

非常感谢你们

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by HKYSIO** [comment]
3.11.11下载速度确实不如前面几个版本，UI界面显示好像也有问题

**Comment by wsjmxz** [comment]
3.11.11都登录不了了，还说什么下载

**Comment by HKYSIO** [comment]
> 刚推出新版本我就更新了，没有遇到你所说的问题，最近几天没有使用

**Comment by wsjmxz** [comment]
> > 刚推出新版本我就更新了，没有遇到你说的问题，最近几天没有用

我也是才从11.10更新到11.11，登录一直转圈圈。

**Comment by onvz** [comment]
我还是在用3.11.5版,,主要阿里云都是用来下载,速度很重要,,虽然隔几个小时就要重新登陆一次,但值得

3.11.5版一直都可以登陆

**Comment by wsjmxz** [comment]
> 我还是用3.11.5版本,,主要阿里云都是用来下载,速度很重要,,虽然隔几个小时就要重新登陆一次,但值得
> 
> 3.11.5版一直都可以登陆

我马上试试

**Comment by onvz** [comment]
> > 我还是用3.11.5版本,,主要阿里云都是用来下载,速度很重要,,虽然隔几个小时就要重新登陆一次,但值得
> > 3.11.5版一直都可以登陆
> 
> 尝试了，依然转圈圈。无语

你有试过官方的客户端吗?如果依然登陆不了,应该就是账号问题了
