### ISSUE TITLE
[Bug] {{相册不显示.}}

### ISSUE THREAD

**Issue by jlu511** [gaozhangmin/aliyunpan#198]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.11

### 系统 System

win10

### 复现步骤 Reproduce step

登录后，相册不显示，空白，换账号也一样，重置软件，重新登录还是一样。
![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/6e4f1ce8-d3cb-44de-a6f6-2b1f9412cbf8)

### 你看到了什么错误？What errors do you see?

相册是空白，左边能看到相册目录，右边是空白，不显示
![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/5fd58c0f-bec2-46a9-aff3-e212c4483d37)

### 你期望看到什么？What did you expect to see?

正常使用相册

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
贴设置里的小白羊日志看下

**Comment by jlu511** [comment]
12 13:27:21 : success : 小白羊启动
11 22:36:44 : success : 小白羊启动
11 22:35:07 : success : 小白羊启动

**Comment by jlu511** [comment]
日志里没有显示错误，缓存里，已经删除全部数据，重新扫两次码登录了，重复几次都一样

**Comment by gaozhangmin** [comment]
> 日志里没有显示错误，缓存里，已经删除全部数据，重新扫两次码登录了，重复几次都一样

那就奇怪了

**Comment by gaozhangmin** [comment]
@jlu511  你点击某个相册了吗？要点击某个相册才会显示相册照片。默认为了性能。不获取照片。

**Comment by gaozhangmin** [comment]
@jlu511  问题已解决，下个版本会修复

**Comment by jlu511** [comment]
> @jlu511 问题已解决，下个版本会修复

好的，谢谢大佬

**Comment by jlu511** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/5cc32261-d120-4fcb-9e47-045065f1d897)

**Comment by jlu511** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/4a96d452-713e-4840-873f-d488e182b88d)

**Comment by jlu511** [comment]
感谢大佬修复，现在点左侧   图库  ， 可以显示照片，但是点 左侧 的其它 我的相簿  文件夹， 仍然不显示图片。 并且在图库里面，选择一个图片，移动到我的相簿-gggg文件夹，报错，
![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/41098273-ce28-4794-b601-63530d6e82aa)

**Comment by jlu511** [comment]
17 03:01:54 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'next_marker') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'next_marker')
    at Proxy.load_image (file:///D:/Software/Internet%20Software/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%981/resources/app.asar/dist/index.js:221:104938)
17 03:01:54 : danger : unhandledrejection
17 02:58:19 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'next_marker') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'next_marker')
    at Proxy.load_image (file:///D:/Software/Internet%20Software/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%981/resources/app.asar/dist/index.js:221:104938)
17 02:58:17 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'next_marker') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'next_marker')
    at Proxy.load_image (file:///D:/Software/Internet%20Software/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%981/resources/app.asar/dist/index.js:221:104938)
17 02:58:12 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'next_marker') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'next_marker')
    at Proxy.load_image (file:///D:/Software/Internet%20Software/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%981/resources/app.asar/dist/index.js:221:104938)
17 02:58:12 : danger : unhandledrejection
17 02:55:55 : success : 小白羊启动
17 02:54:42 : success : 小白羊启动
16 15:44:56 : success : 小白羊启动
16 09:40:12 : success : 小白羊启动
15 19:17:49 : success : 小白羊启动
15 03:11:29 : success : 小白羊启动
15 03:10:59 : warning : ApiTokenRefreshAccount err=200 
15 03:10:59 : warning : HttpError1 message=timeout of 30000ms exceeded
15 03:10:27 : success : 小白羊启动
15 01:48:35 : success : 小白羊启动
14 20:29:06 : success : 小白羊启动
14 20:28:43 : success : 小白羊启动
14 15:39:49 : success : 小白羊启动

**Comment by jlu511** [comment]
双击左侧  我的相簿 下面的文件夹，如 gggg，仍然会弹出错误
![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/0bce1d2b-a929-4bf1-8c08-125ad2244c62)

**Comment by gaozhangmin** [comment]
@jlu511  账号借我登陆debug下可以吗？在电报群里@我。
