### ISSUE TITLE
小白羊最新版本无法登录阿里云盘账号

### ISSUE THREAD

**Issue by GARNET-CRO** [gaozhangmin/aliyunpan#200]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.11

### 系统 System

win x64

### 复现步骤 Reproduce step

没有

### 你看到了什么错误？What errors do you see?

小白羊最新版本无法登录

### 你期望看到什么？What did you expect to see?

没有

### 还有其他的内容吗？Anything else?

没有

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
我刚试过 可以登录。要不清理缓存 要不换个ip。有可能是被alist接口限流了。

**Comment by GARNET-CRO** [comment]
是点高级选项里的清除缓存还是删除全部数据？

**Comment by GARNET-CRO** [comment]
我看Alist群里说的阿里open的验证被阻断了

**Comment by GARNET-CRO** [comment]
还是不能登录，扫完码以后一直转圈

**Comment by gaozhangmin** [comment]
> 我看Alist群里说的阿里open的验证被阻断了

@GARNET-CRO  是这个原因。

**Comment by lansyy** [comment]
挂梯子能成功登录

**Comment by GARNET-CRO** [comment]
> > 我看Alist群里说的阿里open的验证被阻断了
> 
> @GARNET-CRO 是这个原因。

那应该怎么解决呢？

**Comment by GARNET-CRO** [comment]
> 挂梯子能成功登录

我试试

**Comment by GARNET-CRO** [comment]
> 挂梯子能成功登录

Alist能登上，能看到refresh_token:，小白羊还是不行

**Comment by DanielZWX** [comment]
能挂梯子的，比如用CFW， 加一个RULE,     - DOMAIN,api.nn.ci,Proxy，就可以了

**Comment by wsjmxz** [comment]
我挂了梯子都没办法登录。

**Comment by gaozhangmin** [comment]
3.11.12 已修复

**Comment by wsjmxz** [comment]
> 3.11.12 已修复

我只能说 我爱你！
