### ISSUE TITLE
小白羊最新11.11不能登录，挂梯子也依然不能登录！！

### ISSUE THREAD

**Issue by wsjmxz** [gaozhangmin/aliyunpan#201]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.11

### 系统 System

WIN

### 复现步骤 Reproduce step

本来一直用的3.11.10，好好的，刚刚一打开登陆不了，新版11.11也一样登录不了，不是网络问题，挂梯子依然登录不了。

### 你看到了什么错误？What errors do you see?

本来一直用的3.11.10，好好的，刚刚一打开登陆不了，新版11.11也一样登录不了，不是网络问题，挂梯子依然登录不了。

### 你期望看到什么？What did you expect to see?

如上

### 还有其他的内容吗？Anything else?

如上

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
3.11.12 已修复
