### ISSUE TITLE
夹带私货？

### ISSUE THREAD

**Issue by shemengjia** [gaozhangmin/aliyunpan#203]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

1

### 系统 System

1

### 复现步骤 Reproduce step

![QQ截图20230614020010](https://github.com/gaozhangmin/aliyunpan/assets/32380465/9c5aa32d-19f3-4f3f-97c3-e319c9649788)

### 你看到了什么错误？What errors do you see?

1

### 你期望看到什么？What did you expect to see?

1

### 还有其他的内容吗？Anything else?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
可能是引用的那个三方依赖有问题。我不可能搞这东西在软件里面。
