### ISSUE TITLE
小白羊3.11.12版本打不开

### ISSUE THREAD

**Issue by yuhjifdu** [gaozhangmin/aliyunpan#204]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.12

### 系统 System

Windows7 32位

### 复现步骤 Reproduce step

昨天晚上更新了3.11.12一更新就立马试了，结果发现打不开，弹出一个窗口，3.11.11及之前的版本没有这个弹窗。
![Uploading bandicam 2023-06-14 01-16-53-609.jpg…]()

### 你看到了什么错误？What errors do you see?

到网上查了一下解决方法是更新电脑运行库或重装软件，但都试了没用。
![Uploading Screenshot_2023-06-14-09-13-06-453_com.android.browser.jpg…]()

### 你期望看到什么？What did you expect to see?

希望作者检查一下32位版是不是有什么错误，怎么打不开，我的电脑其他软件正常运行，小白羊3.11.11及之前的版本也正常运行，就3.11.12版本打不开，电脑运行库昨晚已更新。
![Uploading bandicam 2023-06-14 02-43-21-198.jpg…]()

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
https://www.123pan.com/s/wbncVv-pUbcv.html提取码:xby3 
重新下载下。
