### ISSUE TITLE
子文件夹搜索

### ISSUE THREAD

**Issue by sj9481** [gaozhangmin/aliyunpan#206]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

好像不能搜索子文件夹的文件 希望添加这个功能

### 描述 Motivation

我存了很多漫画 按作者分类 如果想单独搜索一个漫画就不能直接搜索出来

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
全盘搜索不行吗
