### ISSUE TITLE
最新版本12下载东西报错

### ISSUE THREAD

**Issue by lyy33441314** [gaozhangmin/aliyunpan#207]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.12

### 系统 System

win10

### 复现步骤 Reproduce step

下载什么都提示Aria2c未知错误

### 你看到了什么错误？What errors do you see?

下载什么都提示Aria2c未知错误

### 你期望看到什么？What did you expect to see?

不知道这个是什么问题 

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Hirrorhh** [comment]
win 11 下载也是提示Aria2c未知错误

**Comment by Aluan1996** [comment]
同样的问题，老板你解决了吗
