### ISSUE TITLE
[Bug] {{传输页面“打开云盘位置”错误}}

### ISSUE THREAD

**Issue by 1049731887** [gaozhangmin/aliyunpan#208]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.13

### 系统 System

Windows10

### 复现步骤 Reproduce step

上传图片到相册，在传输页面，点击打开云盘位置，并非跳转到对面位置。

### 你看到了什么错误？What errors do you see?

在传输页面，点击打开云盘位置，并非跳转到对面位置

### 你期望看到什么？What did you expect to see?

应该跳转到相册位置。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
这个问题影响还好。暂时不打算修复。
