### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by Andyqi0076** [gaozhangmin/aliyunpan#21]
不知道是不是我这边的特例，下载文件时，已经设置了下载文件的保存位置，但是点击开始下载，还会一直提示未设置保存路径，无法正常下载，只有设置了默认此路径为下载路径，貌似才可以下载，不知道能否修复一下，感谢！

**Comment by gaozhangmin** [comment]
这个是正常的。必须勾选默认此luj

**Comment by Andyqi0076** [comment]
最早的小白羊是没有这个问题的，所以现在版本限制是没办法恢复了呗，最新版只能这样咯。。。感谢大佬

> 这个是正常的。必须勾选默认此luj

**Comment by hangxj** [comment]
用的是人家蜗牛云盘的接口，因为第二次扫码，提示的是蜗牛云盘申请授权

然后下载依然不快
