### ISSUE TITLE
上传文件夹里面有子文件夹会多次重新创建文件夹[Bug] {{请输入标题，不要留空 - Please enter a title, do not leave it blank.}}

### ISSUE THREAD

**Issue by 421634065** [gaozhangmin/aliyunpan#210]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.14

### 系统 System

win10

### 复现步骤 Reproduce step

上传得文件夹里面含有子文件夹  上传得时候 会把子文件夹也在当前上传位置重新创建一个新得

### 你看到了什么错误？What errors do you see?

上传得文件夹里面含有子文件夹  上传得时候 会把子文件夹也在当前上传位置重新创建一个新得

### 你期望看到什么？What did you expect to see?

上传得文件夹里面含有子文件夹  上传得时候 会把子文件夹也在当前上传位置重新创建一个新得

### 还有其他的内容吗？Anything else?

上传得文件夹里面含有子文件夹  上传得时候 会把子文件夹也在当前上传位置重新创建一个新得

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
这问题很久了 我之前以为已经修复了。我仔细研究下

**Comment by 421634065** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/26759389/2753fc5e-0827-4a5c-a34f-162f85de4733)
![image](https://github.com/gaozhangmin/aliyunpan/assets/26759389/eb440032-a85f-4eb1-a886-895ebba9406d)

**Comment by 421634065** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/26759389/a64ede00-b711-42c7-b6e1-91dc5c8d6930)

**Comment by gaozhangmin** [comment]
windows下文件分隔符不应该是反斜杠 \ 吗，你这怎么是 / ?

**Comment by 421634065** [comment]
这是你得小白羊 子文件成了 /  新文件夹

**Comment by 421634065** [comment]
难道 这就是你BUG所在 写错符号了###

**Comment by gaozhangmin** [comment]
@421634065  等下 给你个测试版本，帮我测试下。

**Comment by gaozhangmin** [comment]
@421634065  https://www.123pan.com/s/wbncVv-Ebbcv.html

**Comment by 421634065** [comment]
修复好了 但是 这个版本感觉比以前卡点 感觉响应差点 可能目前高峰期吧

**Comment by 421634065** [comment]
你这个测试版本喜欢自己莫名后台下载 什么情况

**Comment by gaozhangmin** [comment]
我什么都没改，就改了 一行代码。别瞎说

**Comment by 421634065** [comment]
你这个测试版本 我不知道什么情况 重新打开 疯狂下载星辰变

**Comment by 421634065** [comment]
你这个测试版本 我不知道什么情况 重新打开 疯狂下载星辰变

**Comment by gaozhangmin** [comment]
截图我看看。有可能是我这电脑中毒了

**Comment by 421634065** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/26759389/93e2cedc-24de-492a-a638-b025db63728a)

**Comment by gaozhangmin** [comment]
疯狂下载星辰变 什么是星辰变

**Comment by gaozhangmin** [comment]
截图 我看看。

**Comment by 421634065** [comment]
我删了
重新装最新版本

**Comment by 421634065** [comment]
用了你原版得14没问题 你得测试版本 疯狂乱下载网盘东西

**Comment by 421634065** [comment]
什么时候正式修复这个问题  你上次发我得那个测试版本真得有病毒么

**Comment by 421634065** [comment]
新版本总算修复了  但是那天得测试版本一直下网盘得文件很迷
