### ISSUE TITLE
3.11.14开机启动后很长时间窗口黑屏，请问是软件问题还是电脑问题？谢谢！

### ISSUE THREAD

**Issue by deming831** [gaozhangmin/aliyunpan#211]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.14

### 系统 System

win10,21H1

### 复现步骤 Reproduce step

小白羊3.11.14设置了开机自启动，之前的版本都是很顺利启动和登录，但是新版本后开机显示大概几分钟的黑屏，然后就正常

### 你看到了什么错误？What errors do you see?

暂无

### 你期望看到什么？What did you expect to see?

希望修复

### 还有其他的内容吗？Anything else?

暂无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
ok 我修复下
