### ISSUE TITLE
win11 64 下载提示Aria2c未知错误 试了多个版本都是

### ISSUE THREAD

**Issue by Hirrorhh** [gaozhangmin/aliyunpan#213]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.14

### 系统 System

win 10

### 复现步骤 Reproduce step

下载任何文件都是Aria2c未知错误 试了多个版本都是

### 你看到了什么错误？What errors do you see?

Aria2c未知错误

### 你期望看到什么？What did you expect to see?

正常下载

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Hirrorhh** [comment]
是win 11提示错误

**Comment by Aluan1996** [comment]
兄弟，可以帮我弄一下吗？我加你QQ
