### ISSUE TITLE
3.11.15无法上传文件，出现提醒[504InvalidParameter,CheckNameMod……系统WIN10，下载的安装文件是XBYDriver-3.11.15-win

### ISSUE THREAD

**Issue by deming831** [gaozhangmin/aliyunpan#215]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

XBYDriver-3.11.15-win

### 系统 System

win10,21H1

### 复现步骤 Reproduce step

下载文件无问题，上传文件出现错误，提示504InvalidParameter,CheckNameMod

### 你看到了什么错误？What errors do you see?

无法上传文件

### 你期望看到什么？What did you expect to see?

解决问题

### 还有其他的内容吗？Anything else?

是下载的安装文件版本不对吗，我看下载包里还有个子文件夹小白羊.3.11.15修复access_token登录？

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
下载错版本了吧。旧版本存在这个问题。

**Comment by deming831** [comment]
那应该下载哪个文件啊？谢谢
| |
德明
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月25日 13:31 |
| 收件人 | gaozhangmin/aliyunpan ***@***.***> |
| 抄送人 | deming831 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [gaozhangmin/aliyunpan] 3.11.15无法上传文件，出现提醒[504InvalidParameter,CheckNameMod……系统WIN10，下载的安装文件是XBYDriver-3.11.15-win (Issue #215) |

下载错版本了吧。旧版本存在这个问题。
