### ISSUE TITLE
[Bug] {{aria2c未知错误}}

### ISSUE THREAD

**Issue by Aluan1996** [gaozhangmin/aliyunpan#216]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.15

### 系统 System

win10 64位

### 复现步骤 Reproduce step

每次下载都会出现。aria2c未知错误，更换版本和网上的方法都没有解决。

### 你看到了什么错误？What errors do you see?

aria2c未知错误

### 你期望看到什么？What did you expect to see?

希望看到下载数据

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
这个问题很难排查。极少数会发生这种情况。不知道为什么。

**Comment by Hirrorhh** [comment]
关于这个问题 目前我已经解决 结局方式参考 
1>修改aria2.conf配置文件 增加日志输出,下载文件的时候可以看一下具体错误
2>插件监控一下https://chrome.google.com/webstore/detail/aria2-explorer/mpkodccbngfoacfalldjimigbofkhgjn 自己去配置监控ariac的状态和下载过程  这个软件默认修改了端口号还有增加了secrect  
3>可以自己kill掉aria进程  然后重启 查看状态 首先要保证的是ariac是正常的
![image](https://github.com/gaozhangmin/aliyunpan/assets/30573309/e1472d0a-ee9c-4f15-b2bf-edaa609e3f41)
![image](https://github.com/gaozhangmin/aliyunpan/assets/30573309/87f0da7f-6438-46ff-85ab-1d32b23015ca)

**Comment by Aluan1996** [comment]
关于这个问题 目前我已经解决 结局方式参考
1>修改aria2.conf配置文件 增加日志输出,下载文件的时候可以看一下具体错误(自己搜一下)
2>插件监控一下https://chrome.google.com/webstore/detail/aria2-explorer/mpkodccbngfoacfalldjimigbofkhgjn 自己去配置监控ariac的状态和下载过程 这个软件默认修改了端口号还有增加了secrect
3>可以自己kill掉aria进程 然后重启 查看状态 首先要保证的是ariac是正常的



试过了，插件提示无法连接到aria2。但是任务管理器里面有aria2

**Comment by Hirrorhh** [comment]
> 插件提示无法连接到aria2

所以说要输出日志 还有要自己配置连接端口号和secre

还有种方式:
 log-level=info
 rpc-listen-all=true
 #rpc-secret=S4znWTaZYQi3cpRNb
  rpc-listen-port=6800
  再本地arac页面指定文件和配置  杀掉aaraic进程 然后重启  再打开http://aria2c.com/ 看看输出的日志文件

**Comment by Aluan1996** [comment]
https://github.com/gaozhangmin/aliyunpan/issues/216#issuecomment-1605918780

可以帮我下吗？加你Q或者V

**Comment by Aluan1996** [comment]
@Hirrorhh
可以帮我下吗？加你Q或者V

**Comment by Aluan1996** [comment]
不知道是什么情况，换个WIFI就可以使用了。换回自己的wifi就没法用

**Comment by Hirrorhh** [comment]
我晚上试了一下  是路由器的问题 如果你的路由器二级是路由模式就不行 会找不到ip 目前我还不知道怎么改  但是把二级路由器模式改成扩展就可以了

**Comment by Aluan1996** [comment]
> 我晚上试了一下 是路由器的问题 如果你的路由器二级是路由模式就不行 这样会生成和一级路由不同ip的地址 aira下载的时候找不到这个ip 目前我还不知道怎么改 但是把二级路由器模式改成扩展就可以了

对的，把路由器改成中继模式就没法用报错。改回正常模式就可以了。

**Comment by kindle939393** [comment]
怎么改都不行，请问可以发一个aira2懒人包吗

**Comment by zpoyqx** [comment]
找到一种可能的解决方法：在`aria2.conf`中将`disable-ipv6`改为`true`

**Comment by zpoyqx** [comment]
> 找到一种可能的解决方法：在`aria2.conf`中将`disable-ipv6`改为`true`

`aria2.conf`的`xbyyunpan\resources\engine`下。如果不能解决问题，你可以尝试设置`log`选项，比如`log=D:\ari2.log`，查看error原因，在我的电脑上显示的错误为：`errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.`，通过禁用ipv6得到解决

**Comment by kindle939393** [comment]
> ipv6

可以发一下配置吗，这是我的配置文件，怎么样都不对
[aria2.zip](https://github.com/gaozhangmin/aliyunpan/files/11928616/aria2.zip)

**Comment by Aluan1996** [comment]
https://github.com/gaozhangmin/aliyunpan/issues/216#issuecomment-1615287543

完美解决，是ipv6的问题

**Comment by kindle939393** [comment]
> [#216 (comment)](https://github.com/gaozhangmin/aliyunpan/issues/216#issuecomment-1615287543)
> 
> 完美解决，是ipv6的问题

好像确实是，我电脑IPV6之前关了，开了就能下载了

**Comment by missuor** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/4561294/5d13fbc7-166f-4afe-b58b-a7be237f104a)
这是为解决问题用到的配置，把/opt/小白羊云盘/resources/engine/aria2.conf配置文件里面的async-dns对应值修改为true后能够解决问题。

**Comment by ProgramFan** [comment]
async-dns=true 测试在 Linux 下有用

**Comment by ProgramFan** [comment]
可否将默认的 async-dns 设置为 true？升级新版后，这个值又被改回来了。
