### ISSUE TITLE
左侧目录树能否在右键菜单中添加永久删除选项？

### ISSUE THREAD

**Issue by Yamazaki-wu** [gaozhangmin/aliyunpan#217]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

左侧目录树能否在右键菜单中添加永久删除选项？

### 描述 Motivation

目前左侧目录树的右键菜单只有二级菜单移动到回收站，能否添加一级菜单项永久删除？

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
可以 下个版本
