### ISSUE TITLE
Aria本地连接失败解决方法

### ISSUE THREAD

**Issue by feihongqiuye** [gaozhangmin/aliyunpan#22]
小白羊要安装到的盘路径不能有空格，比如安装到D:/Program Files有空格就不行！！会Aria本地连接失败，会影响下载
路径没有空格就没问题，随便哪个盘都能安装

**Comment by hualinli** [comment]
实测有效。感谢

**Comment by 10152672** [comment]
谢谢hxd

**Comment by pandaliu00** [comment]
Mac 下的同样问题的解决方法该如何处理，感谢

**Comment by luoguanping** [comment]
Mac 下的同样问题的解决方法该如何处理，感谢
