### ISSUE TITLE
[Bug] 更新到MacOS 14后，设置使用Infuse打开视频，随意点击网盘保存的视频，会导致Infuse闪退

### ISSUE THREAD

**Issue by Ssiswent** [gaozhangmin/aliyunpan#222]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.15

### 系统 System

14.0 Beta3

### 复现步骤 Reproduce step

如题，在更新系统前是正常的
设置使用IINA打开视频也正常

### 你看到了什么错误？What errors do you see?

Infuse闪退

### 你期望看到什么？What did you expect to see?

正常使用Infuse打开视频

### 还有其他的内容吗？Anything else?

-

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
那谁让你更新os呢，

**Comment by Ssiswent** [comment]
> 那谁让你更新os呢，

啊这。。。这确实没想到。。。
