### ISSUE TITLE
小白羊3.11.16版本有bug影响使用

### ISSUE THREAD

**Issue by wuyan2005** [gaozhangmin/aliyunpan#224]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

windows 11

### 复现步骤 Reproduce step

使用区间选择无法使用鼠标滚轮滑动页面

### 你看到了什么错误？What errors do you see?

使用区间选择无法使用鼠标滚轮滑动页面

### 你期望看到什么？What did you expect to see?

1

### 还有其他的内容吗？Anything else?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
我这可以滚啊 你截图看看

**Comment by wuyan2005** [comment]
https://github.com/gaozhangmin/aliyunpan/assets/50704364/65eeaa61-d649-465f-b8e9-40a5ba59b6cf

**Comment by wuyan2005** [comment]
然后我实测下来3.11.15能跑满100MB下载3.11.16同样16线程下载只能跑到40MB
