### ISSUE TITLE
上传文件夹，上传成功后，文件夹里面的文件和文件夹会在同一个目录里，文件并没有在原来的文件夹里面

### ISSUE THREAD

**Issue by LIUBANGJIAN** [gaozhangmin/aliyunpan#226]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

win2021

### 复现步骤 Reproduce step

上传文件夹，上传成功后，文件夹里面的文件和文件夹会在同一个目录里，文件并没有在原来的文件夹里面

### 你看到了什么错误？What errors do you see?

上传文件夹，上传成功后，文件夹里面的文件和文件夹会在同一个目录里，文件并没有在原来的文件夹里面

### 你期望看到什么？What did you expect to see?

希望修复bug

### 还有其他的内容吗？Anything else?

希望修复bug

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@LIUBANGJIAN  等下个版本修复
