### ISSUE TITLE
播放一个视频后，右侧的滚动条不能滚动了

### ISSUE THREAD

**Issue by xingsuxingchen** [gaozhangmin/aliyunpan#227]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

windows10-1909

### 复现步骤 Reproduce step

播放视频后 无法滚动滚动条

### 你看到了什么错误？What errors do you see?

播放视频后 无法滚动滚动条

### 你期望看到什么？What did you expect to see?

滚动条滚动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@xingsuxingchen  等下个版本修复
