### ISSUE TITLE
[Bug]在有几十个文件夹的目录下，选择其中几个文件夹后，无法上下滚动继续选择其它文件夹

### ISSUE THREAD

**Issue by reidmex** [gaozhangmin/aliyunpan#229]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

Windows 11

### 复现步骤 Reproduce step

1、某个目录下有几十上百个文件夹
2、进入该目录，选中其中十几个文件夹
3、此时需要继续选中更多文件夹，发现文件夹无法上下滚动，键盘和鼠标都无法滚动

### 你看到了什么错误？What errors do you see?

文件夹无法上下滚动，键盘和鼠标都无法滚动

### 你期望看到什么？What did you expect to see?

可以上下滚动，选择任意多个文件夹

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
3.11.16-Fix修复了这个。公众号更新了

**Comment by reidmex** [comment]
已经解决
