### ISSUE TITLE
[Bug]批量下载几十个文件夹内容的时候，无法正常显示下载速度和进度

### ISSUE THREAD

**Issue by reidmex** [gaozhangmin/aliyunpan#230]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

Windows 11

### 复现步骤 Reproduce step

批量下载几十个文件夹内容的时候，在下载页面无法正常显示下载速度和进度

### 你看到了什么错误？What errors do you see?

下载速度和进度都看不到

### 你期望看到什么？What did you expect to see?

在下载页面可以正常显示下载速度和进度

### 还有其他的内容吗？Anything else?

如果同时下载的文件比较少，比如少于10个，可以正常显示。多了就不行。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@reidmex  截图看下。

**Comment by reidmex** [comment]
问题不重现。
