### ISSUE TITLE
本地调试的时候，总是弹出广告，怎么屏蔽

### ISSUE THREAD

**Issue by liufenix** [gaozhangmin/aliyunpan#232]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

win,mac

### 复现步骤 Reproduce step

yarn run dev

### 你看到了什么错误？What errors do you see?

1

### 你期望看到什么？What did you expect to see?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liufenix** [comment]
![image](https://github.com/gaozhangmin/aliyunpan/assets/9946745/795ec555-4c1f-4968-88dc-d22462ec8ffc)

**Comment by gaozhangmin** [comment]
我本地调试都没出现过。这啥玩意。

**Comment by sohero** [comment]
确实有广告！

**Comment by gaozhangmin** [comment]
我怀疑是我引入的一个开源相册 引入的。要看下。

**Comment by gaozhangmin** [comment]
这不行，免费给他们传播广告了。

**Comment by gaozhangmin** [comment]
@liufenix  如果你能帮我定位出来更好

**Comment by liufenix** [comment]
应该是 https://www.pansearch.me/ 这个搜索网站引入的，把浏览器屏蔽广告插件关掉，这个网站会弹这个广告

**Comment by liufenix** [comment]
@gaozhangmin  把搜索那个注释掉就不弹了

**Comment by gaozhangmin** [comment]
去掉这个了
