### ISSUE TITLE
[Bug] 无法翻页查看未完成下载的文件

### ISSUE THREAD

**Issue by supersw2000** [gaozhangmin/aliyunpan#233]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

Win11

### 复现步骤 Reproduce step

开启下载多个文件，暂停下载后，在“传输”->"下载中“页面有很页未完成下载的文件

### 你看到了什么错误？What errors do you see?

无法滚动查看下一页未下载文件，只能看1,2行

### 你期望看到什么？What did you expect to see?

可以正常滚动查看

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
3.11.16-fix 修复了

**Comment by supersw2000** [comment]
thanks
