### ISSUE TITLE
[Bug] 鼠标滚轮/滚动条不生效

### ISSUE THREAD

**Issue by wentlwr** [gaozhangmin/aliyunpan#234]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

win10 LTSC

### 复现步骤 Reproduce step

存放在分享目录中的视频，如果数量较多，且设置使用potplayer播放时，播放完成关闭播放器，此时云盘中滑动鼠标滚轮，没有反应，拖动右侧滚动条也无反应。必须刷新下或者点别的目录再点回来才能翻滚或者拖动

### 你看到了什么错误？What errors do you see?

滑动鼠标滚轮，没有反应，拖动右侧滚动条也无反应

### 你期望看到什么？What did you expect to see?

滚轮滑动时页面相应上移/下移，右侧滚动条可以拖动并且页面也相应上下移动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
3.11.16-fix
修復了

**Comment by SuLingGG** [comment]
> 3.11.16-fix 修復了

3.11.6 版本下，当同时进行的下载任务有很多时，在「传输 - 下载中」界面仍然存在这个问题。
