### ISSUE TITLE
在任何界面，增加全局可以使用快捷键Ctrl+R进行刷新

### ISSUE THREAD

**Issue by abcde696969** [gaozhangmin/aliyunpan#235]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

在任何界面，都可以使用快捷键Ctrl+R进行刷新

### 描述 Motivation

在任何界面，都可以使用快捷键Ctrl+R进行刷新

### Solution

在任何界面，都可以使用快捷键Ctrl+R进行刷新

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
好注意。支持
