### ISSUE TITLE
[Bug] {{小白羊中文件夹右键颜色标记和视频播放完毕后的自动标记会在小白羊重启后消失}}

### ISSUE THREAD

**Issue by waitwindo** [gaozhangmin/aliyunpan#237]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

windows 10

### 复现步骤 Reproduce step

放映室功能只能看最近看了哪些的视频，但标记文件夹功能在标记各类型资料重要程度的时候还是挺有用的，如果大佬有空的话希望修复下，感谢

### 你看到了什么错误？What errors do you see?

如题

### 你期望看到什么？What did you expect to see?

如题

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by waitwindo** [comment]
或者说能否优化一下，比如 右侧放映室默认为时间降序，文件夹栏默认为名称升序，变成独立的，不要改动任意一个就导致另外一个的排序方式也变动了

**Comment by gaozhangmin** [comment]
我测试下来，这个颜色标记功能是正常的呢。
