### ISSUE TITLE
.desktop问题

### ISSUE THREAD

**Issue by Huayuluoshi** [gaozhangmin/aliyunpan#238]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [x] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

Ubuntu2204LTS

### 复现步骤 Reproduce step

直接安装，然后启动器里小白羊没有图标。
可以通过修改desktop文件修复，但是每次都要这样有点麻烦。

### 你看到了什么错误？What errors do you see?

启动器里小白羊没图标

### 你期望看到什么？What did you expect to see?

启动器里小白羊正常显示图标

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
截个图看下呢。@Huayuluoshi

**Comment by Huayuluoshi** [comment]
![截图 2023-07-21 21-28-10](https://github.com/gaozhangmin/aliyunpan/assets/117527694/bf117862-0ce2-48cf-b0c0-407dfb0c88c2)

**Comment by Huayuluoshi** [comment]
啊？没计划吗……好吧……
不过我的建议是，你可以在网盘启动的时候提醒下用户去公众号里看篇文章……
