### ISSUE TITLE
升级检测有问题

### ISSUE THREAD

**Issue by grassRice** [gaozhangmin/aliyunpan#239]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.9

### 系统 System

windows

### 复现步骤 Reproduce step

用 3.11.9 版本 点击 检查更新

### 你看到了什么错误？What errors do you see?

提示 3.11.9 版本 比 最新的版本 3.11.16 更新，所以没法 自己升级

### 你期望看到什么？What did you expect to see?

如果在用版本是3.11.9 最新版本 3.11.16，在检查更新时，应该 不会出现 比 最新版本更新的 鬼畜 提示
期望 在检查更新 对比版本时，不要 用 字符串 比较，要 一个段一个段的比较，以免出现 明明 版本较低，却 无法 使用 本程序升级的现象

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
新版本以后就没这个问题
