### ISSUE TITLE
登录页面无法跳转问题

### ISSUE THREAD

**Issue by gaozhangmin** [gaozhangmin/aliyunpan#24]
登录页面无法跳转的问题，旧版本也存在，https://github.com/liupan1890/aliyunpan/issues/766。
这个我个人感觉是服务端的问题。我本地无力修复。
如果遇到无法跳转问题，打开下方的二维码URL，直接扫码登录即可。

**Comment by yingxxff** [comment]
可是我这扫码为啥扫不了
