### ISSUE TITLE
浏览文件时如果拖动滚动条，就会卡住

### ISSUE THREAD

**Issue by taswsz** [gaozhangmin/aliyunpan#240]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

windows11

### 复现步骤 Reproduce step

浏览文件时，拖动滚动条，就会卡住，使用滚轮也无法上下滑动，滚动条也无法再拖动。点击其他文件夹或其他位置恢复正常

### 你看到了什么错误？What errors do you see?

浏览文件时，拖动滚动条，就会卡住，使用滚轮也无法上下滑动，滚动条也无法再拖动。点击其他文件夹或其他位置恢复正常

### 你期望看到什么？What did you expect to see?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by taswsz** [comment]
而且，点击全选按钮后，也没法再上下滑动了

**Comment by taswsz** [comment]
在浏览下载界面的时候，可能我一次性下载较多，共一百多个文件，鼠标滚轮下滑了约10分之一位置，就完全卡住了，只能重启软件

**Comment by qNwNp** [comment]
在linux中有同样的问题

**Comment by Yamazaki-wu** [comment]
> 而且，点击全选按钮后，也没法再上下滑动了

我是多选5、6个文件然后就没法滚动了。只能选择旁边的目录树就好了。
刚实测了一下，多选3个文件没问题，选4个及以上就会锁定滚动。

**Comment by Michael-J-ScofieldOVO** [comment]
上传文件的时候也是   无法拉动滚动条

**Comment by gaozhangmin** [comment]
16 Fix版本 这个问题修过了
