### ISSUE TITLE
[Bug]win arm64版本提示“找不到 \resources\engine\aria2c.exe”

### ISSUE THREAD

**Issue by AsrielXuwu** [gaozhangmin/aliyunpan#242]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.7

### 系统 System

Windows11 22H2 22621.2070

### 复现步骤 Reproduce step

点击下方Aria状态，提示找不到 \resources\engine\aria2c.exe
onerror Uncaught Error: Unhandled error. (undefined)
onerror Unhandled error. (undefined)

### 你看到了什么错误？What errors do you see?

下方显示Aria已断开，无法正常启动下载，点击之后提示找不到 \resources\engine\aria2c.exe
onerror Uncaught Error: Unhandled error. (undefined)
onerror Unhandled error. (undefined)

### 你期望看到什么？What did you expect to see?

期望看到下载正常进行

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
打包匆忙，忘记添加aria2c了
