### ISSUE TITLE
[Code] 3.11.17 的代码没merge到主分支 

### ISSUE THREAD

**Issue by virtual-matrix** [gaozhangmin/aliyunpan#245]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.17

### 系统 System

aa

### 复现步骤 Reproduce step

⏰

### 你看到了什么错误？What errors do you see?

⏰

### 你期望看到什么？What did you expect to see?

⏰

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
之前没来得及，现在更新了
