### ISSUE TITLE
每次上传文件的时候，都要询问一遍"遇到重名文件冲突"的提示吗？

### ISSUE THREAD

**Issue by By-Tian** [gaozhangmin/aliyunpan#25]
每次上传文件的时候，都要询问一遍"遇到重名文件冲突"的提示吗？
没有可以设置关掉这个提示吗，我经常都要上传文件，老是提示好麻烦。。。。。

![企业微信截图_16805981237189](https://user-images.githubusercontent.com/70208411/229739955-bc47e552-efc9-4577-8db0-464466bea39d.png)

**Comment by gaozhangmin** [comment]
> 每次上传文件的时候，都要询问一遍"遇到重名文件冲突"的提示吗？ 没有可以设置关掉这个提示吗，我经常都要上传文件，老是提示好麻烦。。。。。
> 
> ![企业微信截图_16805981237189](https://user-images.githubusercontent.com/70208411/229739955-bc47e552-efc9-4577-8db0-464466bea39d.png)

已解决，看我最新发布
