### ISSUE TITLE
[Bug] {{无法新建分享链接}}

### ISSUE THREAD

**Issue by linyin022** [gaozhangmin/aliyunpan#250]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.18

### 系统 System

Windows 11

### 复现步骤 Reproduce step

选中文件夹后创建分享链接会报错

### 你看到了什么错误？What errors do you see?

![image](https://github.com/gaozhangmin/aliyunpan/assets/95907705/210413a6-13ad-4c5b-884d-55f57054e6d1)

### 你期望看到什么？What did you expect to see?

希望能修复这个bug

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@linyin022 我这边可以
