### ISSUE TITLE
启动以后，提示：列出文件夹失败error 403

### ISSUE THREAD

**Issue by wedkskskl** [gaozhangmin/aliyunpan#251]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.18

### 系统 System

win10

### 复现步骤 Reproduce step

![Dingtalk_20230803172736](https://github.com/gaozhangmin/aliyunpan/assets/88787604/f70c4282-a6ce-4b24-8f55-9a06d4f6af5f)
![Dingtalk_20230803172758](https://github.com/gaozhangmin/aliyunpan/assets/88787604/2a220937-9b12-42f7-8a1c-a8acda683b2c)

### 你看到了什么错误？What errors do you see?

1

### 你期望看到什么？What did you expect to see?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
重新登录
