### ISSUE TITLE
[Bug] {{由于新版增加了资源库，导入文件时只能先导入资源库才能再转移到网盘，希望早日能解决.}}

### ISSUE THREAD

**Issue by iD2073** [gaozhangmin/aliyunpan#253]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.18

### 系统 System

Win11

### 复现步骤 Reproduce step

不能导入分享的资源

### 你看到了什么错误？What errors do you see?

由于没有资源库无法导入分享的资源

### 你期望看到什么？What did you expect to see?

希望早日解决

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Eyion** [comment]
在资源盘中进行导入分享，alipan.com无法导入，提示必须是aliyundrive.com，同时导入框的分享链接无法粘贴链接，只能手动输入。
