### ISSUE TITLE
关于速度，跑不满带宽

### ISSUE THREAD

**Issue by liangcun8** [gaozhangmin/aliyunpan#254]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

关于速度，跑不满带宽

### 描述 Motivation

关于速度，跑不满带宽

### Solution

关于速度，跑不满带宽

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by LancerCH77** [comment]
类似问题，同一个资源，3.11.15版本可以跑满千兆带宽，下载速度基本100M/s，后续的几个版本包括最新3.11.19，都只能跑到50M/s左右，设置都一样。现在只能保持2个版本都放在电脑中，望解决。

**Comment by gaozhangmin** [comment]
> 类似问题，同一个资源，3.11.15版本可以跑满千兆带宽，下载速度基本100M/s，后续的几个版本包括最新3.11.19，都只能跑到50M/s左右，设置都一样。现在只能保持2个版本都放在电脑中，望解决。

@LancerCH77 那我给你一个测试版本 你测试下速度。微信公众号联系下我
