### ISSUE TITLE
[Bug]不显示任何资源，显示空白

### ISSUE THREAD

**Issue by wedkskskl** [gaozhangmin/aliyunpan#256]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.19fix

### 系统 System

win10

### 复现步骤 Reproduce step

【1】清理数据库、清理缓存、删除全部数据（重置）、卸载软件重新安装都不起作用，显示空白没有资源
【2】删除全部数据（重置）之后，二维码一直加载不出来，需要3次才能成功

### 你看到了什么错误？What errors do you see?

https://github.com/gaozhangmin/aliyunpan/assets/88787604/43fae0a3-b131-406a-a827-fb63e1380807

### 你期望看到什么？What did you expect to see?

1

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
你知道备份盘和资源盘有什么区别吗

**Comment by ElkGetLost** [comment]
不显示任何资源，显示空白+1

**Comment by lesca** [comment]
不显示任何资源，显示空白+1
