### ISSUE TITLE
[Bug]无法“区间选择”文件

### ISSUE THREAD

**Issue by supersw2000** [gaozhangmin/aliyunpan#259]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.18

### 系统 System

Win11

### 复现步骤 Reproduce step

文件下载页面
1.点击“区间选择”
2.选择一个文件
3.再选择一个

### 你看到了什么错误？What errors do you see?

没有批量选中文件

### 你期望看到什么？What did you expect to see?

批量选中文件
<img width="598" alt="屏幕截图 2023-08-08 095145" src="https://github.com/gaozhangmin/aliyunpan/assets/62132282/a78853b7-e10a-4f96-beba-13fa06c25aa9">

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by iD2073** [comment]
是你使用的方式不对吧，我刚才试了一下，正常的啊

**Comment by supersw2000** [comment]
> 是你使用的方式不对吧，我刚才试了一下，正常的啊
你能确认么？
我是在"传输->下载"页面有这个问题。
“网盘”页面没有这个问题
