### ISSUE TITLE
[Bug] 目前可以从资源盘移动或复制到备份盘，但是从备份盘到资源盘没有移动入口。

### ISSUE THREAD

**Issue by iD2073** [gaozhangmin/aliyunpan#260]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.19

### 系统 System

Win11

### 复现步骤 Reproduce step

目前可以从资源盘移动或复制到备份盘，但是从备份盘到资源盘没有移动入口。

### 你看到了什么错误？What errors do you see?

目前可以从资源盘移动或复制到备份盘，但是从备份盘到资源盘没有移动入口。

### 你期望看到什么？What did you expect to see?

希望解决

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
接口不支持这样操作。
