### ISSUE TITLE
资源库和备份盘的问题

### ISSUE THREAD

**Issue by wsjmxz** [gaozhangmin/aliyunpan#266]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.16

### 系统 System

WIN

### 复现步骤 Reproduce step

希望支持资源盘的查看，目前阿里云的新策略把资源盘和备份盘分开了，并不是有什么BUG，求作者大大！

### 你看到了什么错误？What errors do you see?

希望支持资源盘的查看，目前阿里云的新策略把资源盘和备份盘分开了，并不是有什么BUG，求作者大大！

### 你期望看到什么？What did you expect to see?

希望支持资源盘的查看，目前阿里云的新策略把资源盘和备份盘分开了，并不是有什么BUG，求作者大大！

### 还有其他的内容吗？Anything else?

希望支持资源盘的查看，目前阿里云的新策略把资源盘和备份盘分开了，并不是有什么BUG，求作者大大！

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
早就支持了，谁让你不关注公众号
@wsjmxz

**Comment by wsjmxz** [comment]
我关注了啊！！天地良心啊！！

**Comment by lentikr** [comment]
@gaozhangmin 
似乎资源盘和备份盘的入口反了，我只给了软件访问资源盘的权限，但资源盘中的文件却出现在备份盘的入口中，资源盘部分是空。
![image](https://github.com/gaozhangmin/aliyunpan/assets/95539012/6c4e16b0-2bb4-400d-b139-011e4eced0a7)
