### ISSUE TITLE
建议把启动后的界面设置成资源盘而不是现在的备份盘，资源盘空间大，最常用

### ISSUE THREAD

**Issue by abcde696969** [gaozhangmin/aliyunpan#267]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

建议把启动后的界面设置成资源盘而不是现在的备份盘，资源盘空间大，最常用

### 描述 Motivation

建议把启动后的界面设置成资源盘而不是现在的备份盘，资源盘空间大，最常用。或者在软件的“设置”里给一个设置，让用户自己选择启动时候是停留在哪个盘。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by wsjmxz** [comment]
资源盘和备份盘 只需要鼠标点一下就切换了，已经很完美了。作者大大幸苦

**Comment by abcde696969** [comment]
> 资源盘和备份盘 只需要鼠标点一下就切换了，已经很完美了。作者大大幸苦

维护确实辛苦，但还是希望能修改一下。毕竟每次打开小白羊的第一件事都是做这个切换操作，一天两天还行，天天（次次）都重复这个操作确实很有些烦恼。PS：另外再提一个bug：最新版，无法通过“加载视频同名字幕”功能自动匹配网盘里的字幕，现在只能选择“手动选择字幕”功能进行手动匹配。
