### ISSUE TITLE
Ctrl+A（全选），ESC（取消）这些之前版本可以使用的快捷键全部失效

### ISSUE THREAD

**Issue by abcde696969** [gaozhangmin/aliyunpan#272]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.19

### 系统 System

win11

### 复现步骤 Reproduce step

3.11.19版本，Ctrl+A（全选），ESC（取消）这些之前版本可以使用的快捷键全部失效

### 你看到了什么错误？What errors do you see?

3.11.19版本，Ctrl+A（全选），ESC（取消）这些之前版本可以使用的快捷键全部失效

### 你期望看到什么？What did you expect to see?

Ctrl+A（全选），ESC（取消）这些快捷键正常使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
下个版本会解决。原因是因为加资源盘，导致冲突了。
