### ISSUE TITLE
最新版无法重置设置为默认设置

### ISSUE THREAD

**Issue by xiaozhi1218** [gaozhangmin/aliyunpan#273]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.19

### 系统 System

win11 22H2

### 复现步骤 Reproduce step

1. 修改设置的某些参数选项
2. 选择高级选项中的 清理数据库、清理缓存、删除全部数据(重置)，重启后都无法将我修改的设置恢复为默认设置

### 你看到了什么错误？What errors do you see?

1. 修改设置的某些参数选项
2. 选择高级选项中的 清理数据库、清理缓存、删除全部数据(重置)，重启后都无法将我修改的设置恢复为默认设置

### 你期望看到什么？What did you expect to see?

1. 能将我修改的设置恢复为默认设置

### 还有其他的内容吗？Anything else?

1. 希望增加一个重置设置的按钮选项，防止自己不小心修改了某些设置参数，但是忘记修改的选项是哪一些，这时候能重置为默认设置。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
最老版本也没有这个功能啊。

**Comment by xiaozhi1218** [comment]
> 最老版本也没有这个功能啊。

请问这个重置设置功能有计划开发吗

**Comment by gaozhangmin** [comment]
> > 最老版本也没有这个功能啊。
> 
> 
> 
> 请问这个重置设置功能有计划开发吗

你赞助成为会员 我可以帮你开发。
