### ISSUE TITLE
3.11.19 不支持导入的分享转存至资源盘

### ISSUE THREAD

**Issue by xuanzhiyouxuan001** [gaozhangmin/aliyunpan#276]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.19

### 系统 System

Windows 10 2009

### 复现步骤 Reproduce step

1，3.11.19 不支持导入的分享转存至资源盘 转存默认资源盘 
应该要像官方一样 可以选择存到资源盘还是备份盘
![image](https://github.com/gaozhangmin/aliyunpan/assets/54681896/26d9559f-7025-4052-bb70-d7f9dd4681e9)

2，安装新版本小白羊后 清空的之前导入的分享 
导入分享不易 一安装新版本就全清空了 有点难受
![image](https://github.com/gaozhangmin/aliyunpan/assets/54681896/d58a4633-d143-46e1-8eab-010907710977)

### 你看到了什么错误？What errors do you see?

1，3.11.19 不支持导入的分享转存至资源盘 转存默认资源盘 
应该要像官方一样 可以选择存到资源盘还是备份盘
![image](https://github.com/gaozhangmin/aliyunpan/assets/54681896/26d9559f-7025-4052-bb70-d7f9dd4681e9)

2，安装新版本小白羊后 清空的之前导入的分享 
导入分享不易 一安装新版本就全清空了 有点难受
![image](https://github.com/gaozhangmin/aliyunpan/assets/54681896/d58a4633-d143-46e1-8eab-010907710977)

### 你期望看到什么？What did you expect to see?

1，转存应该要像官方一样 可以选择存到资源盘还是备份盘
2， 安装新版本小白羊 导入过的分享 应该保留 或者说提供是否保留的开关

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by zhannao456** [comment]
官方app也只知道导入外部分享到资源盘。
我刚测试过最新版本，卸载重装，并不会删除导入的记录。

**Comment by gaozhangmin** [comment]
@xuanzhiyouxuan001 @xuanzhiyouxuan001  官方app也只支持导入分享到资源盘。
我刚测试过，卸载重装app并不会清楚导入记录。
