### ISSUE TITLE
[Bug] 缓存目录无法修改

### ISSUE THREAD

**Issue by jlu511** [gaozhangmin/aliyunpan#277]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.22

### 系统 System

win10

### 复现步骤 Reproduce step

![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/04d46329-9863-40f4-a4d1-c00b6e4aee9c)
缓存路径之前版本可以修改，最新版无法修改，这个功能是改回去了吗？

### 你看到了什么错误？What errors do you see?

![image](https://github.com/gaozhangmin/aliyunpan/assets/64378673/04d46329-9863-40f4-a4d1-c00b6e4aee9c)
缓存路径之前版本可以修改，最新版无法修改，这个功能是改回去了吗？

### 你期望看到什么？What did you expect to see?

恢复缓存目录设置功能

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
之前版本可以修改，但是有Bug。综合考虑下来，这个功能可有可无，就去掉了

**Comment by Ghiclgi** [comment]
感觉这个功能还是很重要的，对于有免安装需求的人来说
