### ISSUE TITLE
新增的Alist功能如何使用

### ISSUE THREAD

**Issue by DanielZWX** [gaozhangmin/aliyunpan#280]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.22

### 系统 System

Ubuntu 22.04

### 复现步骤 Reproduce step

点击“资源分享”中的“Alist”，就显示一个登录页面，这是哪一个站点的？

### 你看到了什么错误？What errors do you see?

点击“资源分享”中的“Alist”，就显示一个登录页面，这是哪一个站点的？

### 你期望看到什么？What did you expect to see?

难道不是应该增加一个个站点 或者 选择指定的Alist站点吗

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
你看下alist官网介绍咋用的

**Comment by gaozhangmin** [comment]
> 我也是懵的 alist不是本来就能挂载阿里云盘open吗？ 跟这个软件有什么关联？

@gzxiexl   Alist支持很多网盘，不只是阿里云盘。
