### ISSUE TITLE
[Bug] 发现两个问题：1,图片和视频缩略图都不显示，2，相册里上传的视频文件依然不能播放和下载

### ISSUE THREAD

**Issue by iD2073** [gaozhangmin/aliyunpan#281]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.22

### 系统 System

Win11

### 复现步骤 Reproduce step

发现三个问题：1,图片和视频缩略图都不显示，2，相册里上传的视频文件依然不能播放和下载。3，希望标题栏功能切换的时候不要左右移位，让小白羊和版本号 一直显示就好。

### 你看到了什么错误？What errors do you see?

略

### 你期望看到什么？What did you expect to see?

略

### 还有其他的内容吗？Anything else?

略

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
第一个修好啦，第2个本来就不支持，也不打算支持

**Comment by iD2073** [comment]
既然修复了，为什么下载下来问题还是有呢？是需要清空数据库吗？还有上面的功能区的按钮能不能固定啊，切换的时候左右来回跳来跳去的，

**Comment by gaozhangmin** [comment]
下错版本了吧。我验证过的
