### ISSUE TITLE
[Bug] {{赞赏后没解锁会员功能}}

### ISSUE THREAD

**Issue by 13071558875** [gaozhangmin/aliyunpan#284]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.22

### 系统 System

Win11H22

### 复现步骤 Reproduce step

打赏并备注手机号了，但是还是没有解锁会员功能

### 你看到了什么错误？What errors do you see?

会弹出一个json错误

### 你期望看到什么？What did you expect to see?

解锁会员功能

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
公众号私聊我，发截图看看
