### ISSUE TITLE
目录上传问题

### ISSUE THREAD

**Issue by whatrye** [gaozhangmin/aliyunpan#29]
选取一个目录整个上传，结果并没有建立目录，保持目录结构，而是把目录名和文件名拼接在一起作为文件名了。
比如上传AA目录，下面有bb,cc,dd文件，结果是在当前目录下生成了以AA/bb,AA/cc,AA/dd为文件名的3个文件。

**Comment by gaozhangmin** [comment]
> 选取一个目录整个上传，结果并没有建立目录，保持目录结构，而是把目录名和文件名拼接在一起作为文件名了。 比如上传AA目录，下面有bb,cc,dd文件，结果是在当前目录下生成了以AA/bb,AA/cc,AA/dd为文件名的3个文件。

见我最新版修复v3.11.4
