### ISSUE TITLE
[Bug] {{软件开启后报错，Aria2已断开，无法下载网盘文件.}}

### ISSUE THREAD

**Issue by spss1019** [gaozhangmin/aliyunpan#290]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

XBYDriver-3.11.22-win-x64

### 系统 System

win11

### 复现步骤 Reproduce step

运行程序就跳错误提示框，移开可正常浏览、设置，但无法下载文件。点错误框的×，软件自动退出。

### 你看到了什么错误？What errors do you see?

![360截图20230905192707397](https://github.com/gaozhangmin/aliyunpan/assets/144123279/cd996f6b-87d2-4573-becd-5cff9e16d6e3)
![360截图20230905193225548](https://github.com/gaozhangmin/aliyunpan/assets/144123279/20670506-9102-44c4-94fc-2636de39ec62)
![360截图20230905193321872](https://github.com/gaozhangmin/aliyunpan/assets/144123279/d71678fb-3a57-4c0f-a0fe-f17c0cf1c645)

### 你期望看到什么？What did you expect to see?

解除错误提示，正常上传下载

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by ha757575** [comment]
安装最新版3.11.23，运行时360报木马病毒

木马名称：HEUR/QVM202.0.C64A.Malware.Gen
所在路径：D:\program files\xby\resources\engine\alist.exe

**Comment by FengZhongShaoNian** [comment]
我在Linux上使用的3.11.24版本 也遇到了同样的问题

**Comment by Huayuluoshi** [comment]
ubuntu2204运行3.11.26报错
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
AriaAddUrl Cannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:12722) at async DownDAL.aSpeedEvent (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:120:19166)
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:41074) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:48895)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:41074) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:48895)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:41074) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:48895)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:41074) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:48895)
Uncaught Error: Unhandled error. (undefined)
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:41074) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:101:48895)
小白羊启动

**Comment by Huayuluoshi** [comment]
@gaozhangmin

**Comment by sorgs** [comment]
ubuntu 运行3.12.1 报错


24 21:01:30 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612)
    at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433)
24 21:01:30 : danger : onerror
24 21:01:29 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612)
    at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433)
24 21:01:29 : danger : onerror
24 21:01:28 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612)
    at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433)
24 21:01:28 : danger : onerror
24 21:01:27 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612)
    at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433)
24 21:01:27 : danger : Uncaught Error: Unhandled error. (undefined)
24 21:01:26 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612)
    at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433)
24 21:01:26 : danger : Uncaught Error: Unhandled error. (undefined)
24 21:00:57 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 21:00:47 : success : 小白羊启动

**Comment by Huayuluoshi** [comment]
> ubuntu 运行3.12.1 报错
> 
> 24 21:01:30 : danger : onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433) 24 21:01:30 : danger : onerror 24 21:01:29 : danger : onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433) 24 21:01:29 : danger : onerror 24 21:01:28 : danger : onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433) 24 21:01:28 : danger : onerror 24 21:01:27 : danger : onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433) 24 21:01:27 : danger : Uncaught Error: Unhandled error. (undefined) 24 21:01:26 : danger : onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at re.emit (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:59612) at ue.onerror (file:///opt/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98/resources/app.asar/dist/index.js:95:67433) 24 21:01:26 : danger : Uncaught Error: Unhandled error. (undefined) 24 21:00:57 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400 24 21:00:47 : success : 小白羊启动

解决方法：
0.Ubuntu系统
1.打开终端，执行“apt download  aria2”
2.解压，在aria2的deb包中找到“aria2c.so”文件
3.在小白羊的安装目录下找到同名文件，替换即可。

**问题产生原因：小白羊和Ubuntu的aria2不兼容，用系统源中的文件替换即可
