### ISSUE TITLE
插件里扫描重复文件功能失效，非SVIP

### ISSUE THREAD

**Issue by wuyou1024** [gaozhangmin/aliyunpan#291]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.23

### 系统 System

window11

### 复现步骤 Reproduce step

扫描后什么都扫描不出来

### 你看到了什么错误？What errors do you see?

rt

### 你期望看到什么？What did you expect to see?

rt

### 还有其他的内容吗？Anything else?

rt

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by ha757575** [comment]
安装最新版3.11.23，运行时360报木马病毒

木马名称：HEUR/QVM202.0.C64A.Malware.Gen
所在路径：D:\program files\xby\resources\engine\alist.exe
