### ISSUE TITLE
第一次打开时显示列出文件出错[Bug] {{请输入标题，不要留空 - Please enter a title, do not leave it blank.}}

### ISSUE THREAD

**Issue by jackkyzjr** [gaozhangmin/aliyunpan#292]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.23

### 系统 System

win11

### 复现步骤 Reproduce step

第一次打开，出现列出文件出错
就是说看不到网盘里的文件

### 你看到了什么错误？What errors do you see?

第一次打开，出现列出文件出错
就是说看不到网盘里的文件

### 你期望看到什么？What did you expect to see?

正确列出文件

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by ha757575** [comment]
安装最新版3.11.23，运行时360报木马病毒

木马名称：HEUR/QVM202.0.C64A.Malware.Gen
所在路径：D:\program files\xby\resources\engine\alist.exe

**Comment by jackkyzjr** [comment]
so，What's the resolvation？

**Comment by gaozhangmin** [comment]
> 安装最新版3.11.23，运行时360报木马病毒
> 
> 木马名称：HEUR/QVM202.0.C64A.Malware.Gen 所在路径：D:\program files\xby\resources\engine\alist.exe

这个应该是误报 我是从alist官网下载的alist 程序

**Comment by gaozhangmin** [comment]
@jackkyzjr  你退出来 重新登录下就行
