### ISSUE TITLE
[Bug] {{mac版本播放视频，不能外挂字幕。}}

### ISSUE THREAD

**Issue by romerise** [gaozhangmin/aliyunpan#293]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.23

### 系统 System

macOS 10.13.6

### 复现步骤 Reproduce step

1. 播放视频
2. 字幕设置
3. 无可用字幕
4. 浏览器上看有字幕
<img width="808" alt="000" src="https://github.com/gaozhangmin/aliyunpan/assets/7501408/91146f60-608e-4cb3-b4da-230828163f71">
<img width="918" alt="001" src="https://github.com/gaozhangmin/aliyunpan/assets/7501408/a97fc3ab-cf95-4035-a73b-9f0bc3562c49">

### 你看到了什么错误？What errors do you see?

以上

### 你期望看到什么？What did you expect to see?

以上

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
字幕开关都是关着的

**Comment by gaozhangmin** [comment]
@romerise  可以把这个视频分享给我 我本地试下。分享链接发这里。

**Comment by gaozhangmin** [comment]
这个我确认过了，是因为经过阿里云盘的转码后，字幕和音轨都会丢失

**Comment by romerise** [comment]
> 这个我确认过了，是因为经过阿里云盘的转码后，字幕和音轨都会丢失

https://www.aliyundrive.com/s/5BfAMT7SgDP
官网客户端我看了下是能挂字幕的。
