### ISSUE TITLE
[小白羊影视网站如何登录？登录界面提示用谷歌账户登录，点击链接无反应，谢谢Bug] {{请输入标题，不要留空 - Please enter a title, do not leave it blank.}}

### ISSUE THREAD

**Issue by deming831** [gaozhangmin/aliyunpan#299]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.24

### 系统 System

win10,21H1

### 复现步骤 Reproduce step

小白羊影视网站无法登录，点击登录跳出用谷歌登录界面，但点击链接无反应

### 你看到了什么错误？What errors do you see?

小白羊影视网站无法登录，点击登录跳出用谷歌登录界面，但点击链接无反应

### 你期望看到什么？What did you expect to see?

希望能指导如何登录

### 还有其他的内容吗？Anything else?

暂无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
Google要翻墙。
