### ISSUE TITLE
登录时候显示三个错误码

### ISSUE THREAD

**Issue by Huowuge** [gaozhangmin/aliyunpan#3]
登录显示错误码，mac电脑
![Snipaste_2023-04-01_10-24-03](https://user-images.githubusercontent.com/68574153/229261488-27f14037-a340-4951-8673-4d6f9c870fce.png)

**Comment by Huowuge** [comment]
下载的是你昨晚发的最新mac v3.11.2版本，即使绕开错误尝试登录也失败了。windows还没测试。

**Comment by gaozhangmin** [comment]
重新打开试下 这块是有的问题 我会修复

**Comment by gaozhangmin** [comment]
> 下载的是你昨晚发的最新mac v3.11.2版本，即使绕开错误尝试登录也失败了。windows还没测试。

重试过可以了吗？

**Comment by gaozhangmin** [comment]
这是aria2的错误码。
