### ISSUE TITLE
macOS 无法打开 app（提示应用已损坏），解决方法

### ISSUE THREAD

**Issue by loylou** [gaozhangmin/aliyunpan#30]
M1Max

**Comment by gaozhangmin** [comment]
> M1Max

这个要开苹果开发者账号 要收费，我不想搭钱进去。

**Comment by HiUSB** [comment]
终端中执行  sudo xattr -r -d com.apple.quarantine  /Applications/小白羊云盘.app

**Comment by wangya123456789** [comment]
> 解决方式：关闭SIP后，终端中执行 sudo xattr -r -d com.apple.quarantine /Applications/小白羊云盘.app
实测有用。
