### ISSUE TITLE
[Bug] bind: address already in use

### ISSUE THREAD

**Issue by c02y** [gaozhangmin/aliyunpan#300]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

XBYDriver-3.11.24-linux-x86_64.AppImage

### 系统 System

Arch Linux

### 复现步骤 Reproduce step

无法下载文件，窗口底部显示aria2断开

```
>> ~/Applications/XBYDriver-3.11.24-linux-x86_64.AppImage
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[277850:0912/173407.204424:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
the server is runnint on port 16800
the server is runnint on port 16800
'/tmp/.mount_XBYDri4NCO39/resources/engine/alist server'
'/tmp/.mount_XBYDri4NCO39/resources/engine/alist server'



(node:277850) electron: Failed to load URL: http://127.0.0.1:5244/ with error: ERR_CONNECTION_REFUSED
(Use `xbyyunpan --trace-warnings ...` to show where the warning was created)
启动AList失败 : Error: Command failed: '/tmp/.mount_XBYDri4NCO39/resources/engine/alist' server --data '/home/chz/.config/alixby3/alist-data'
INFO[2023-09-12 17:34:29] reading config file: /home/chz/.config/alixby3/alist-data/config.json
INFO[2023-09-12 17:34:29] load config from env with prefix: ALIST_
INFO[2023-09-12 17:34:29] init logrus...
INFO[2023-09-12 17:34:29] start HTTP server @ 0.0.0.0:5244
FATA[2023-09-12 17:34:29] failed to start http: listen tcp 0.0.0.0:5244: bind: address already in use
```

### 你看到了什么错误？What errors do you see?

杀掉xbyyunpan/aria2c/alist/XBYDriver或者使用`netstat -nap`查看占用的端口再杀掉相关进程再打开还是一样的错误

试了下XBYDriver-3.11.23-linux-x86_64.AppImage，也是同样的问题

XBYDriver-3.11.19-linux-x86_64.AppImage没这个问题，可以正常下载

### 你期望看到什么？What did you expect to see?

可以正常下载文件

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
这个报错和aria2c 无关。且没有影响。你看我置顶的issue了。先kill掉aria2c进程。再重启小白羊试试

**Comment by c02y** [comment]
上面已经提过了
```
杀掉xbyyunpan/aria2c/alist/XBYDriver或者使用netstat -nap查看占用的端口再杀掉相关进程再打开还是一样的错误

试了下XBYDriver-3.11.23-linux-x86_64.AppImage，也是同样的问题

XBYDriver-3.11.19-linux-x86_64.AppImage没这个问题，可以正常下载
```

**Comment by c02y** [comment]
修复了吗？

上次我说[启动时间太长超过45秒的issue](https://github.com/gaozhangmin/aliyunpan/issues/243)就突然被关闭了，到现在也是没解决
这次我说有bind的问题无法下载，也没解决就这么被关闭了？

如果你那边没问题无法复现也没必要关闭啊，有什么疑问继续沟通就行，不管是解决不了还是懒得解决，像这样什么都不说就关闭issue不合适吧

**Comment by m2cc** [comment]
一样现在一直报这个错了
