### ISSUE TITLE
第二次扫码后后跳转网页让你下载APP

### ISSUE THREAD

**Issue by liveskai** [gaozhangmin/aliyunpan#301]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.24

### 系统 System

win10 22H2

### 复现步骤 Reproduce step

第一次扫描确认登录后再弹出一个二维码，扫后是在APP内跳转网页让你下载APP

### 你看到了什么错误？What errors do you see?

登录不了

### 你期望看到什么？What did you expect to see?

能登录

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by MarkZhangGZ** [comment]
3.11.24  在ubuntu上也出现楼主完全一样的问题。
第一次扫描确认登录后再弹出一个二维码，扫后是在APP内跳转网页让你下载APP

**Comment by gaozhangmin** [comment]
这个问题已经重复很多遍了。是阿里云盘app的问题。请使用微信扫码
