### ISSUE TITLE
相册无法显示视频，只能显示图片

### ISSUE THREAD

**Issue by zlbwswws95** [gaozhangmin/aliyunpan#303]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.25

### 系统 System

windows11

### 复现步骤 Reproduce step

打开相册，只能显示图片，显示不了自动备份的视频

### 你看到了什么错误？What errors do you see?

打开相册，只能显示图片，显示不了自动备份的视频

### 你期望看到什么？What did you expect to see?

无

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
这个相册 就只能显示照片。暂时不考虑视频
