### ISSUE TITLE
[Bug] {{使用内置播放器播放视频时，外挂字幕无法识别且无法手动加载，播放器设置中显示无可用字幕}}

### ISSUE THREAD

**Issue by 1825265352** [gaozhangmin/aliyunpan#304]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.24

### 系统 System

win7和win10 1909

### 复现步骤 Reproduce step

使用内置播放器，播放带有外置字幕的视频，外挂字幕无论放在该视频同文件夹内或者其子目录下，外挂字幕都无法识别且无法手动加载，播放器设置中显示无可用字幕

### 你看到了什么错误？What errors do you see?

外挂字幕都无法识别且无法手动加载，播放器设置中显示无可用字幕，字幕设置里“字幕开关”选项无法打开。
![image](https://github.com/gaozhangmin/aliyunpan/assets/145309847/3118495e-52b1-4e09-8910-1168f9810ef3)

![image](https://github.com/gaozhangmin/aliyunpan/assets/145309847/e3650e3e-ba9a-43e3-a11d-8cb6b8f14148)

### 你期望看到什么？What did you expect to see?

希望内置播放器可以正常使用外挂字幕功能

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@1825265352 @1825265352  文件分享给我。我看下。

**Comment by gaozhangmin** [comment]
下个版本修好

**Comment by 1825265352** [comment]
视频及相关字幕文件如下：https://www.aliyundrive.com/s/99C8Pj1vbee

**Comment by gaozhangmin** [comment]
3.11.26 已解决
