### ISSUE TITLE
切换用户失败

### ISSUE THREAD

**Issue by mayitbe11** [gaozhangmin/aliyunpan#307]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.25

### 系统 System

win10.0.19045.2130

### 复现步骤 Reproduce step

成功登录第二个用户名，并切换至上一个用户时，报错

### 你看到了什么错误？What errors do you see?

23 09:53:58 : danger : errorHandler 
//== Error ==//
 Cannot read properties of undefined (reading 'localeCompare') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at file:///C:/Yue/Backup/Internet/xbyyunpan/resources/app.asar/dist/index.js:63:40802
    at Array.sort (<anonymous>)
    at UserDAL.GetUserList (file:///C:/Yue/Backup/Internet/xbyyunpan/resources/app.asar/dist/index.js:63:40783)
    at ReactiveEffect.fn (file:///C:/Yue/Backup/Internet/xbyyunpan/resources/app.asar/dist/index.js:243:124473)

### 你期望看到什么？What did you expect to see?

成功切换至其他用户

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by LIUBANGJIAN** [comment]
我只能显示一个用户，登录第二个用户，第一个用户就消失了。

**Comment by gaozhangmin** [comment]
OK          找到问题了

**Comment by gaozhangmin** [comment]
3.11.26 已解决
