### ISSUE TITLE
作者能修复下内置网页播放器吗

### ISSUE THREAD

**Issue by RinSky123** [gaozhangmin/aliyunpan#31]
我目前遇到的问题分别是:
1、选择了字幕但是显示不出来
2、关闭窗口的时候会卡一下才关闭

**Comment by gaozhangmin** [comment]
> 我目前遇到的问题分别是: 1、选择了字幕但是显示不出来 2、关闭窗口的时候会卡一下才关闭

可以看看

**Comment by mxhx** [comment]
另外可以增加播放器进度条可以预览画面吗？

**Comment by gaozhangmin** [comment]
目前正在修复这个播放器。
