### ISSUE TITLE
保存播放画质

### ISSUE THREAD

**Issue by 67906980725** [gaozhangmin/aliyunpan#314]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

播放连续剧集时记住切换的画质

### 描述 Motivation

当网络状况不太理想的时候, 播放转码视频的默认高画质可能会有卡顿或影响局域网内其它设备网络的情况, 需要手动切换到较低一些的画质. 如果播放的是连续剧就不得不每播一集就手动切换一次画质, 这样就显得有些麻烦.

### Solution

 希望播放视频功能可以增加自动记忆切换使用的播放画质的功能

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
这个可以有

**Comment by gaozhangmin** [comment]
3.12.1已支持
