### ISSUE TITLE
大佬好，PC新版 上传 不稳定，且上传不可断点断续

### ISSUE THREAD

**Issue by Cribug666** [gaozhangmin/aliyunpan#317]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.26

### 系统 System

win10

### 复现步骤 Reproduce step

上传的速度上下波动很大，不稳定。

而且如上传时暂停，换到公司继续上传则显示上传失败（群里的几个人皆是如此）。

### 你看到了什么错误？What errors do you see?

如标题和复现步骤所示，望大佬修复。

### 你期望看到什么？What did you expect to see?

🙏

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
换ip 不能断点的问题 在排查了
