### ISSUE TITLE
登录后卡在【正在加载用户信息】

### ISSUE THREAD

**Issue by benzBrake** [gaozhangmin/aliyunpan#32]
![加载信息](https://user-images.githubusercontent.com/11323774/230312834-8d071748-0e6c-4777-b8a6-f7a2179ab9b4.jpg)

**Comment by gaozhangmin** [comment]
你要清空原来的安装数据

**Comment by hangxj** [comment]
用的是人家蜗牛云盘的接口，因为第二次扫码，提示的是蜗牛云盘申请授权

**Comment by gaozhangmin** [comment]
> 用的是人家蜗牛云盘的接口，因为第二次扫码，提示的是蜗牛云盘申请授权

有什么问题？

**Comment by benzBrake** [comment]
> 你要清空原来的安装数据

我卸载重装两次了

**Comment by gaozhangmin** [comment]
> > 你要清空原来的安装数据
> 
> 
> 
> 我卸载重装两次了

设置里有清空数据的选择。点下
