### ISSUE TITLE
致敬傻逼白嫖党的 - “你也太恶心了吧”

### ISSUE THREAD

**Issue by itworkzhang** [gaozhangmin/aliyunpan#326]
### Search before asking

- [X] 在 [issues](https://github.com/gaozhangmin/aliyunpan/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### feature

s

### 描述 Motivation

卧槽 你这个网站也太多广告了吧 x-movie.netlify.xxx 简直比360还恶心  借着别人的开源 不是搞广告 就是搞会员制 真恶心

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@itworkzhang 
致敬傻逼白嫖党：
1. 我最早发布这个网站的时候就说过：我没有任何收入来自这个网站。
![image](https://github.com/gaozhangmin/aliyunpan/assets/9278488/5bb5154a-fc24-4a4e-bfb1-08093f1f5a32)
2. 该项目确实是基于前人的开发，我没有拿之前任何的功能来卖会员，所有需要会员的功能都是我开发的。
你这种白嫖党抓紧去死一死
