### ISSUE TITLE
v3.11.4的release的版本问题

### ISSUE THREAD

**Issue by koomi** [gaozhangmin/aliyunpan#33]
如图，烦请更正。
感谢你的付出！
![Snipaste_2023-04-06_21-31-06](https://user-images.githubusercontent.com/669217/230393829-71bb7aeb-59af-43f7-af8f-697b0aa01b19.jpg)

**Comment by jjjyyyllll** [comment]
下载下来 程序还是3.11.3？？ 是打错了吗

**Comment by koomi** [comment]
> 下载下来 程序还是3.11.3？？ 是打错了吗

下下来的还是v3.11.3
![Snipaste_2023-04-06_22-56-36](https://user-images.githubusercontent.com/669217/230418340-33edd907-8fda-4e6d-913e-84d2531f3c33.jpg)

**Comment by gaozhangmin** [comment]
最新已经修改
