### ISSUE TITLE
[Bug] 关于新出的影院模式的几点反馈

### ISSUE THREAD

**Issue by douseful** [gaozhangmin/aliyunpan#341]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

v3.12.1

### 系统 System

macOS 13.4

### 复现步骤 Reproduce step

无

## 画面非全屏状态异常拉伸。
正常全屏状态：
<img width="1920" alt="image" src="https://github.com/gaozhangmin/aliyunpan/assets/52767905/ef137fcf-0585-4f90-bf1b-d5e45e8208f4">
异常非全屏状态：
<img width="858" alt="image" src="https://github.com/gaozhangmin/aliyunpan/assets/52767905/c7e9b276-dd56-4635-94c4-9a807a21f2e5">

## 在加载出了某个剧集的信息后，**切换左侧列表后**画面和信息并没有相应改变。
<img width="858" alt="image" src="https://github.com/gaozhangmin/aliyunpan/assets/52767905/4cd0dd07-2a28-4a59-be25-31c3951fa9e0">

### 你期望看到什么？What did you expect to see?

如上

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
OK  我看下。谢谢反馈
