### ISSUE TITLE
[Bug] {{无法导入alipan.com/s/xxx此类分享链接}}

### ISSUE THREAD

**Issue by jiang911105** [gaozhangmin/aliyunpan#358]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.12.2

### 系统 System

Windows 10

### 复现步骤 Reproduce step

无

### 你看到了什么错误？What errors do you see?

阿里云盘最近出现的新的分享链接，不是aliyundrive开头的了，是alipan.com/s/xxx这种类型，点开软件无法复制导入这种链接，打开无反应

### 你期望看到什么？What did you expect to see?

无

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by ppllpig** [comment]
+1，要手动翻译地址

**Comment by ldqs365** [comment]
无法识别别的网址，但是直接复制/s/后面的内容就可以直接读取了
