### ISSUE TITLE
V3.11.4 下载路径只能在设置中选定，无法在下载时自定义

### ISSUE THREAD

**Issue by Yamazaki-wu** [gaozhangmin/aliyunpan#36]
必须开启“默认此路径为下载路径”
否则在自定义下载路径时会提示“未设置保存路径”
烦请作者大大修复一下。

**Comment by gaozhangmin** [comment]
这个是在预期之中的的呢。官方app也是这样

**Comment by Yamazaki-wu** [comment]
> 这个是在预期之中的的呢。官方app也是这样

大佬能否麻烦添加一下这个功能呢？
