### ISSUE TITLE
[Bug] 插件无法使用，提示错误

### ISSUE THREAD

**Issue by wuzhen819** [gaozhangmin/aliyunpan#365]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.12.3

### 系统 System

win10

### 复现步骤 Reproduce step

插件-重复文件扫描，加载列表

### 你看到了什么错误？What errors do you see?

![6f635092306bc915fd00364cba51003](https://github.com/gaozhangmin/aliyunpan/assets/49865145/5ff8ff77-bada-46b9-9b48-c548e6e3c798)

### 你期望看到什么？What did you expect to see?

扫描成功

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@wuzhen819  这个是提示数据库太大了，你清理下缓存吧

**Comment by wuzhen819** [comment]
> @wuzhen819 这个是提示数据库太大了，你清理下缓存吧

清了缓存，但没有效果，缓存大小没有变化，是否还有其他处理方法？
![image](https://github.com/gaozhangmin/aliyunpan/assets/49865145/7dce1218-08e5-451c-91d9-cdb184bf55a9)

**Comment by wuzhen819** [comment]
> @wuzhen819 这个是提示数据库太大了，你清理下缓存吧

清理缓存，自动重启后还是报同样的错误

**Comment by wuzhen819** [comment]
> @wuzhen819 这个是提示数据库太大了，你清理下缓存吧

已经解决了，重置了本地数据库，重新登录就可以了
