### ISSUE TITLE
付款后无法解锁

### ISSUE THREAD

**Issue by DifferentSparkler** [gaozhangmin/aliyunpan#378]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.12.4

### 系统 System

安卓，win

### 复现步骤 Reproduce step

扫码付款后登录没有自动解锁，自助网站也打不开，尝试过开启或者不开科学都无法打开。

### 你看到了什么错误？What errors do you see?

![Screenshot_2024-01-17-18-37-59-79_3915bacb930634b](https://github.com/gaozhangmin/aliyunpan/assets/38945550/4b995df1-baa1-4405-b682-cf1adc7d32ff)
，一直在扫描支付界面不能自动跳转

### 你期望看到什么？What did you expect to see?

自动解锁

### 还有其他的内容吗？Anything else?

没有了

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Ddddj9808** [comment]
我也是这样 下了1.0.9版之后 配置源后显示是这样的
![f9138149682417a0f715e1e4cdf3ca4d](https://github.com/gaozhangmin/aliyunpan/assets/156869778/7ea306a0-c953-4a95-afc8-07d4bb894129)
原来下的是1.0.6版 赞赏后会自动配置好源 但是播放视频有声音但黑屏 不知道为什么

Uploading 65701.mp4…
现在又下回了.6版 但是电视直播台只能看到cctv13和浙江卫视 别的全黑屏跳掉了 也不知道为啥

**Comment by DifferentSparkler** [comment]
什么情况呀 还能不能解决呀

**Comment by gaozhangmin** [comment]
退款给你了

**Comment by DifferentSparkler** [comment]
现在能不能用呀，修复了没有呀
