### ISSUE TITLE
能否把上传文件的“开始上传”提示框取消，拖入文件就直接上传

### ISSUE THREAD

**Issue by By-Tian** [gaozhangmin/aliyunpan#38]
上次反馈没说清楚，v3.11.4只是取消的上传时文件名称冲突的提示（整合到了“设置”里面）

我其实是想说把整个上传提示框都取消的，直接拖动文件到小白羊就直接上传，像小白羊V2那样，主要是我零碎文件多，上传多少个，就得点多少次“开始上传”，挺烦人的。。。

还有，v3.11.4，上传文件失败，提示 504，创建文件失败（数据错误）
![企业微信截图_16808297776332](https://user-images.githubusercontent.com/70208411/230520946-a6e14aed-3c96-43c0-879f-7cf12f81342a.png)
![企业微信截图_16808298822049](https://user-images.githubusercontent.com/70208411/230520955-3c97360f-95e3-4e1f-ad71-91eb0c91c3ad.png)

**Comment by By-Tian** [comment]
上一个版本，上传文件是没有问题，应该是这个版改出问题了

**Comment by gaozhangmin** [comment]
可以在设置中增加一次性设置，默认还是得让用户确认选择的文件夹是否正确

**Comment by By-Tian** [comment]
> 

好的，主要是现在的版本，都没有的可以设置的地方。烦人
