### ISSUE TITLE
上传zip文件失败了，报错504创建文件失败（数据错误）

### ISSUE THREAD

**Issue by 454592673** [gaozhangmin/aliyunpan#40]
![image](https://user-images.githubusercontent.com/22283930/230537158-82a681c5-f47e-48d1-9bfe-b535c84ee600.png)

**Comment by Andyqi0076** [comment]
同样报错，清除全部数据重置仍未解决，烦请作者帮忙查一下，谢谢！

**Comment by gaozhangmin** [comment]
> 同样报错，清除全部数据重置仍未解决，烦请作者帮忙查一下，谢谢！

已经修复了 还没release
