### ISSUE TITLE
[Bug] {{ VersionError The requested version (20) is less than the existing version (30) }}

### ISSUE THREAD

**Issue by mayitbe11** [gaozhangmin/aliyunpan#416]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.13.2, 3.13.3

### 系统 System

win10 22H2 19045.2130

### 复现步骤 Reproduce step

启动小白羊云盘，登录阿里云账号时即出现错误信息。

### 你看到了什么错误？What errors do you see?

03 14:30:32 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///C:/ xxx/xbyyunpan/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///C:/Yue/Back...
03 14:30:32 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///C:/ xxx/xbyyunpan/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///C:/Yue/Back...
03 14:30:32 : danger : unhandledrejection
03 14:30:32 : warning : _ApiDirFileListCount err=root 403
03 14:30:32 : warning : _ApiDirFileListCount err=root 403
03 14:30:31 : warning : ApiUserPic err=401
03 14:30:20 : success : 小白羊启动
03 14:29:51 : warning : ApiUserDriveFileCount1 err= 403
03 14:29:47 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///C:/ xxx/xbyyunpan/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///C:/Yue/Back...
03 14:29:47 : danger : aReloadUploaded 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///C:/ xxx/xbyyunpan/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///C:/Yue/Back...
03 14:29:47 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///C:/ xxx/xbyyunpan/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///C:/Yue/Back...
03 14:29:47 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///C:/ xxx/xbyyunpan/resources/app.asar/dist/index.js:22:76513
    at executePromiseTask (file:///C:/Yue/Back...
03 14:29:47 : warning : ApiUserDriveFileCount1 err= 403
03 14:29:47 : warning : _ApiDirFileListCount err=root 403
03 14:29:47 : warning : _ApiDirFileListCount err=root 403
03 14:29:46 : warning : ApiUserPic err=401
03 14:29:33 : success : 小白羊启动

### 你期望看到什么？What did you expect to see?

无报错

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by FoXiBoy** [comment]
兄弟我和你一样

**Comment by missbear9527** [comment]
尝试退出所有账号，重新登录试一下

**Comment by mayitbe11** [comment]
退出账号，并清理数据库后，问题解决。

**Comment by FoXiBoy** [comment]
按照方法尝试并无效果，依然报错






                       
原始邮件
                       
                     

发件人："mayitbe11"< ***@***.*** &gt;;

发件时间：2024/4/15 19:55

收件人："gaozhangmin/aliyunpan"< ***@***.*** &gt;;

抄送人："FoXiBoy"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [gaozhangmin/aliyunpan] [Bug] {{ VersionError The requestedversion (20) is less than the existing version (30) }} (Issue #416)




 
退出账号，并清理数据库后，问题解决。
