### ISSUE TITLE
关于下载速度问题

### ISSUE THREAD

**Issue by StrollStars** [gaozhangmin/aliyunpan#429]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.13.3

### 系统 System

Win7

### 复现步骤 Reproduce step

直接通过资源盘的下载按钮进行下载，观察传输中的速度。

### 你看到了什么错误？What errors do you see?

下载速度估算不超过2MBps，原先可以跑满带宽。

### 你期望看到什么？What did you expect to see?

能够跑满带宽。

### 还有其他的内容吗？Anything else?

是和最近出台的三方应用权益包有关吗？

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Lioncky** [comment]
哈哈哈 逼氪可惜zip都下载不了

**Comment by StrollStars** [comment]
发现重启能够恢复正常下载，先关闭了。
