### ISSUE TITLE
Aria2本地连接失败

### ISSUE THREAD

**Issue by gaozhangmin** [gaozhangmin/aliyunpan#5]
## 现在小白羊支持配置本地aria2c，并启动了，不用依赖程序里面的aria2c。详见v3.11.4

针对aria 本地连接失败问题的说明:
1. 小白羊在启动时候，会通过命令aria2c 在本地启动一个aria2c的服务端进程，如果本地连接失败，那就是服务端启动失败。
2. 目前了解到的服务端启动失败的原因有：小白羊安装路径有空格。 这个我在本地能复现，并且已经修复，下个版本release。

**Comment by President6** [comment]
确实好了

**Comment by YeTianXingShi** [comment]
这个问题可以考虑通过别的方式解决吗？ 因为我是习惯不分盘用户。并且挺多程序都用aria2的

**Comment by gaozhangmin** [comment]
> 这个问题可以考虑通过别的方式解决吗？ 因为我是习惯不分盘用户。并且挺多程序都用aria2的

去研究研究

**Comment by daxiong007** [comment]
我这边发现的是aria2所在路径不能有空格，和[odomu](https://github.com/odomu/aliyunpan)的版本一样，比如：D:\Program Files\aliyunpan，这样就会一直提示断开连接，安装到D:\aliyunpan就没问题，可以正常使用。

**Comment by HYliangkai** [comment]
macos有这个问题怎么解决啊QAQ

**Comment by asca0121** [comment]
> 

是的，或者安装到默认位置就好了。

**Comment by lmm214** [comment]
> 3\. aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800

本地重新安装 aria2 再手动输入命令，搞定～

**Comment by ch634421335** [comment]
有个问题就是我本地没有安装 aria2，而且我也不想安装，但是还是会一直弹这个错误，有什么解决方法吗？

**Comment by EKyero** [comment]
> macos有这个问题怎么解决啊QAQ

你可能安装过基于 aria2 的软件？brew install aria2 试试

**Comment by cuichacha** [comment]
Mac环境，手动安装Aria2并启动服务，依旧出现【本地连接已断开】，麻烦大佬看下
<img width="676" alt="image" src="https://user-images.githubusercontent.com/12711401/229969146-d4725dc8-89e8-4c19-9065-18c8986c2cf3.png">

**Comment by ShenTJ2000** [comment]
感谢，实测有效，放到D盘根目录就解决了。

**Comment by maomaochong199** [comment]
/electron/main/index.ts   里面的引用打包aria2c路径写错了 ` const subprocess = spawn(
      ariaPath,
      [`应该写为` const subprocess = spawn(
      ariaPath2,
      [`

不然程序运行时call的路径只有aria2c，识别不到打包的aria2c，需要使aria2c安装在$PATH目录下。
经测试arm64架构下打包的aria2c仍是x86_64位linux的，手动替换arm64的可执行文件后能正常运行了。

**Comment by maomaochong199** [comment]
@gaozhangmin    如果aria2c的16800端口被另一个程序占用，程序会以16800依次递增一位的端口如16801启动aria2c，但是aliyunpan仍以16800去连接aria2c，导致连接不到aria2c

**Comment by gaozhangmin** [comment]
> @gaozhangmin    如果aria2c的16800端口被另一个程序占用，程序会以16800依次递增一位的端口如16801启动aria2c，但是aliyunpan仍以16800去连接aria2c，导致连接不到aria2c

现在支持配置本地aria2c了你可以下载static/engine/aria.conf到本地配合本地的aria2c启动。你说的问题 新版本已经修复了。不存在这个问题了。

**Comment by lclrc** [comment]
启动小白羊之后有aria2c进程:

![](https://user-images.githubusercontent.com/23278764/230728035-b528e12c-95cb-4529-92b4-7fae285c29d8.png)

任意开始一个下载任务之后, 进程消失, 并且任务卡住:

![](https://user-images.githubusercontent.com/23278764/230728074-f7947d69-0e69-426e-bf3c-cbf5b1384bd4.png)

debug了下, 在设置了本地aria2c路径和配置文件路径之后, 重启动xby, 会执行到`SaveSetting()`, 导致设置恢复到原来样子. 再看了眼源码发现读取配置的时候就没有读取`localAria2cPath`和`localAria2cConfPath`, 保存了个寂寞.
另外图里同样的aria2c命令手动执行可以正常下载, xby自动带起来的aria2c就会错误, 同一个`aria2c`命令和配置文件.

**Comment by hy546880109** [comment]
mac 使用 aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800 依然报错
<img width="781" alt="image" src="https://user-images.githubusercontent.com/44777854/231217647-5c30fbf7-78dd-455f-b786-bfbf823ef32b.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/44777854/231217737-941896ca-9299-4c6a-ada6-3f08896f9254.png">

**Comment by cuichacha** [comment]
> mac 使用 aria2c --enable-rpc --rpc-listen-all=true --listen-port 16800 依然报错
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/44777854/231217647-5c30fbf7-78dd-455f-b786-bfbf823ef32b.png">
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/44777854/231217737-941896ca-9299-4c6a-ada6-3f08896f9254.png">

你上面这个启动失败的错是没有配置文件导致的，但是我配了配置文件，启动成功后，app下载依旧不可用，只能让作者大佬看下了

**Comment by wengzhenquan** [comment]
Mac咋用

**Comment by maomaochong199** [comment]
> /electron/main/index.ts 里面的引用打包aria2c路径写错了 ` const subprocess = spawn( ariaPath, [`应该写为` const subprocess = spawn( ariaPath2, [`
> 
> 不然程序运行时call的路径只有aria2c，识别不到打包的aria2c，需要使aria2c安装在$PATH目录下。 经测试arm64架构下打包的aria2c仍是x86_64位linux的，手动替换arm64的可执行文件后能正常运行了。

最新发现的问题，还是这里，下面几行，'--listen-port=' + port  改成 '--rpc-listen-port=' + port  才对。自动向16800更高位寻找未被占用端口并连接的功能就正常了。

**Comment by gaozhangmin** [comment]
> > /electron/main/index.ts 里面的引用打包aria2c路径写错了 ` const subprocess = spawn( ariaPath, [`应该写为` const subprocess = spawn( ariaPath2, [`
> > 不然程序运行时call的路径只有aria2c，识别不到打包的aria2c，需要使aria2c安装在$PATH目录下。 经测试arm64架构下打包的aria2c仍是x86_64位linux的，手动替换arm64的可执行文件后能正常运行了。
> 
> 最新发现的问题，还是这里，下面几行，'--listen-port=' + port 改成 '--rpc-listen-port=' + port 才对。自动向16800更高位寻找未被占用端口并连接的功能就正常了。

你这说的不准确，process.chdir(basePath)这个已经切换到执行目录下了。
-rcp-listne-port是给远程下载使用的。本地下载使用listen-port。
