### ISSUE TITLE
启动后报错，无法加载用户信息

### ISSUE THREAD

**Issue by with1874** [gaozhangmin/aliyunpan#53]
登录后头像可以加载，网盘内容刷新不出来
![image](https://user-images.githubusercontent.com/68050803/230774609-1c380c09-8469-46bb-8329-936f061136c4.png)

**Comment by gaozhangmin** [comment]
清理cache, 设置里点一下

**Comment by with1874** [comment]
> 清理cache, 设置里点一下

感谢！清除完后正常使用
