### ISSUE TITLE
文件目录无法重命名

### ISSUE THREAD

**Issue by hy546880109** [gaozhangmin/aliyunpan#59]
![image](https://user-images.githubusercontent.com/44777854/230849206-6fb1cc85-56ff-4930-8214-71072b87e562.png)

**Comment by hy546880109** [comment]
![image](https://user-images.githubusercontent.com/44777854/230849468-3658a58e-7de6-43fd-b9c0-12880531858f.png)

**Comment by gaozhangmin** [comment]
@hy546880109 我试过没问题
