### ISSUE TITLE
最新这个版本更加登录不了啊，第二个二维码出不来

### ISSUE THREAD

**Issue by RinSky123** [gaozhangmin/aliyunpan#6]
昨天的版本退出重进几次是可以出来的，最新这个一直不行，二维码出不来

**Comment by gaozhangmin** [comment]
3.11.2.1吗？出不来，下面有个链接，直接打开扫码。

**Comment by RinSky123** [comment]
> 

是啊，一直提醒让退出重进扫码

**Comment by RinSky123** [comment]
> 3.11.2.1吗？出不来，下面有个链接，直接打开扫码。

![Snipaste_2023-04-02_01-17-40](https://user-images.githubusercontent.com/121341108/229305257-53179727-6e47-4086-ab88-1f5555708080.png)
没有链接啊，它一直这样提示的

**Comment by gaozhangmin** [comment]
> 

你试下最新的v3.11.3。我本地测试过是没问题的。能用在这里反馈下。

**Comment by RinSky123** [comment]
> > 
> 
> 你试下最新的v3.11.3。我本地测试过是没问题的。能用在这里反馈下。

可以了可以了，谢谢大佬
