### ISSUE TITLE
网页内置播放器，可以改成MPVplayer吗

### ISSUE THREAD

**Issue by Shibanyu007** [gaozhangmin/aliyunpan#62]
之前的小白羊网页内置播放器是MPVplayer，现在您发布的是Artplayer，个人感觉还是mpv好用些，比如快捷键控制mpv可以1.1/1.2/1.3....art快捷键只有1.0/1.5。可以考虑换回MPV吗。谢谢，辛苦了

**Comment by gaozhangmin** [comment]
瞎说吧 你自己去原来的小白羊看看代码

**Comment by Shibanyu007** [comment]
哦，确实是我搞错了。我之前用的也不是原版小白羊，是其它修改版https://github.com/PingKuNet/aliyunpan
抱歉

**Comment by jlu511** [comment]
可以换，你自己下个mpv，然后设置里设置下mpv。exe就行了
