### ISSUE TITLE
能提供arm64的版本吗？

### ISSUE THREAD

**Issue by liutun** [gaozhangmin/aliyunpan#64]
现在在用银河麒麟操作系统，希望能提供arm64架构的deb安装包，谢谢。

**Comment by maomaochong199** [comment]
`https://github.com/odomu/aliyunpan  依据这个打包arm64了的v3.10.24版，目前测试能够直接解压运行
 在解压后的目录位置打开终端 输入 ./aliyunpan   , 回车运行 `
如果aria2c不能正常连接检查这两个文件是否有可执行权限-rwxr-xr-x
（目前有一个bug，aria2c的连接端口写死了，如果16800端口被占用，这版会找不到aria2c端口，查看端口占用命令netstat -tlpn）
`ls -alhS aliyunpan
ls -alhS resources\engine\aria2c
sudo chmod 755 aliyunpan
sudo chmod 755 resources\engine\aria2c`
[https://wwrp.lanzout.com/izNZa0snp81g](url)
