### ISSUE TITLE
3.11.4 修复版本仍存在上传文件失败的问题 504 InvalidParameter.CheckNameMode

### ISSUE THREAD

**Issue by L-zee** [gaozhangmin/aliyunpan#69]
![image](https://user-images.githubusercontent.com/45615832/231106000-1ce7a719-7c36-49b5-adc8-9a2ff8154172.png)
日志如下：
11 16:45:10 : success : 小白羊启动
11 16:44:06 : danger : createWithFolders 
//== Error ==//
 InvalidParameter.CheckNameMode AnLinkSetup.exe
11 16:44:06 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:44:04 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:44:01 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:43:59 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:43:57 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:43:55 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:41:53 : danger : createWithFolders 
//== Error ==//
 InvalidParameter.CheckNameMode AnLinkSetup.exe
11 16:41:51 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:41:49 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:41:47 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:41:44 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:41:42 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:40:40 : danger : createWithFolders 
//== Error ==//
 InvalidParameter.CheckNameMode AnLinkSetup.exe
11 16:40:40 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:40:38 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:40:36 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:40:34 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:40:32 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:40:29 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400
11 16:37:27 : success : 小白羊启动

**Comment by gaozhangmin** [comment]
我本地测试都没问题啊

**Comment by gaozhangmin** [comment]
> ![image](https://user-images.githubusercontent.com/45615832/231106000-1ce7a719-7c36-49b5-adc8-9a2ff8154172.png) 日志如下： 11 16:45:10 : success : 小白羊启动 11 16:44:06 : danger : createWithFolders //== Error ==// InvalidParameter.CheckNameMode AnLinkSetup.exe 11 16:44:06 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:44:04 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:44:01 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:43:59 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:43:57 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:43:55 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:41:53 : danger : createWithFolders //== Error ==// InvalidParameter.CheckNameMode AnLinkSetup.exe 11 16:41:51 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:41:49 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:41:47 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:41:44 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:41:42 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:40:40 : danger : createWithFolders //== Error ==// InvalidParameter.CheckNameMode AnLinkSetup.exe 11 16:40:40 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:40:38 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:40:36 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:40:34 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:40:32 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:40:29 : warning : HttpError4 status=400 code=InvalidParameter.CheckNameMode message=Request failed with status code 400 11 16:37:27 : success : 小白羊启动

@L-zee 回复你文件的完整路径。我本地复现，是否能复现。

**Comment by L-zee** [comment]
D:\Downloads\AnLinkSetup.exe
上传到云盘根目录

**Comment by gaozhangmin** [comment]
> D:\Downloads\AnLinkSetup.exe
> 
> 上传到云盘根目录

那有可能 我没测试过windows
