### ISSUE TITLE
如果项目对你有帮助，请考虑捐赠帮助项目持续维护，用爱发电不太能持续哈 

### ISSUE THREAD

**Issue by gaozhangmin** [gaozhangmin/aliyunpan#7]
如果项目对你有帮助，请考虑捐赠帮助项目持续维护，用爱发电不太能持续哈

**Comment by Andyqi0076** [comment]
大佬问一下，是不考虑做一下windows版了吗。。。

**Comment by gaozhangmin** [comment]
> 大佬问一下，是不考虑做一下windows版了吗。。。

不是有包吗？不能用吗？我没有windows电脑。没试过。

**Comment by Andyqi0076** [comment]
> > 大佬问一下，是不考虑做一下windows版了吗。。。
> 
> 不是有包吗？不能用吗？我没有windows电脑。没试过。

刷新了一下出来了。。。感谢，我去试试！您辛苦了！！
