### ISSUE TITLE
上传限速问题

### ISSUE THREAD

**Issue by luzanlu** [gaozhangmin/aliyunpan#70]
千兆带宽上传速度之前一直是40-50M的，现在最高15M，换过几个版本都是这样，用网页版可以满速上传，请问下是什么情况呢？网页版现在经常无故自动退出登录，有时候排队上传几十个文件，自动登出，都不知道哪些传完成，哪些没完成，太麻烦了

**Comment by gaozhangmin** [comment]
网页版已不是我开发的 我怎么知道

**Comment by luzanlu** [comment]
不好意思，我是说用您最新的版本，上传被限速了，不清楚什么原因，因为我的宽带是千兆的，现在上传速度单文件和多文件都是最高速度只有15M

**Comment by luzanlu** [comment]
也不是用了您的软件被限速，而是说用了几个延续版本的小白羊，包括现在您这个最新版本，不清楚什么原因，上传速度只有15M而已，不能满速上传，可以修复一下吗？

**Comment by gaozhangmin** [comment]
> 也不是用了您的软件被限速，而是说用了几个延续版本的小白羊，包括现在您这个最新版本，不清楚什么原因，上传速度只有15M而已，不能满速上传，可以修复一下吗？
阿里云限的速。

**Comment by luzanlu** [comment]
> > 也不是用了您的软件被限速，而是说用了几个延续版本的小白羊，包括现在您这个最新版本，不清楚什么原因，上传速度只有15M而已，不能满速上传，可以修复一下吗？
> > 阿里云限的速。

可是我用网页版却是能满速上传呢？什么原因呀？
还有一个问题，刚发现，可以秒传的文件不能秒传，还是显示上传，我取消上传，用网页版却秒传上去了，您可以测试一下看看

**Comment by gaozhangmin** [comment]
官方新版api不支持妙传了

**Comment by luzanlu** [comment]
好吧，还是谢谢回复，希望能解决小白羊上传限速问题

**Comment by gaozhangmin** [comment]
> 好吧，还是谢谢回复，希望能解决小白羊上传限速问题

那得把阿里云拖出来打一顿，因为是他们限的速
