### ISSUE TITLE
release中可否添加便携包版本？

### ISSUE THREAD

**Issue by wayner6** [gaozhangmin/aliyunpan#72]
rt，本人喜欢将一些好工具的便携包版本整理进一个文件夹里，这样即使重装电脑只需把文件夹迁移，无须重装，并且自定义的设置也可以保留，应该有很多和我一样的同志吧

**Comment by gaozhangmin** [comment]
> rt，本人喜欢将一些好工具的便携包版本整理进一个文件夹里，这样即使重装电脑只需把文件夹迁移，无须重装，并且自定义的设置也可以保留，应该有很多和我一样的同志吧

你先点个star 不过分吧

**Comment by wayner6** [comment]
![image](https://user-images.githubusercontent.com/88063517/231188370-3acfd348-9b6e-4516-97fc-f4dd319b07ff.png)
💯 💯 💯 💯 💯

**Comment by wayner6** [comment]
@gaozhangmin 很多项目都有portable也就是便携版本，它不是单独的一个exe程序，它的数据很多都存储在文件夹里，例如原来的小白羊，它的便携包就是这样的，他需要调用的程序都打包在文件夹里，我不懂这些结构。
![image](https://user-images.githubusercontent.com/88063517/231191962-11912936-46b4-4267-8807-bb2e2b5ee834.png)
很多github项目都有便携包版本的，用起来很舒服

**Comment by gaozhangmin** [comment]
这个就是安装后的应用目录。你可以直接安装后备份目录。

**Comment by jlu511** [comment]
> 

作者这个exe包，可以用winrar直接打开，解压就能运行，安装不安装没啥区别。

**Comment by Ghiclgi** [comment]
作者您好！还有一个问题就是缓存路径在Appdata，原来的小白羊好像是可以自定义的

**Comment by laogoulucky** [comment]
您好，感谢作者，同样也需要便携包版本

**Comment by Ghiclgi** [comment]
> 作者您好！还有一个问题就是缓存路径在Appdata，原来的小白羊好像是可以自定义的

发现3.11.11版本已经可以自定义缓存路径啦！虽然下载的安装包还要安装，但其实已经可以当作便携版使用了！非常赞！

**Comment by ENIAC1729** [comment]
> > 作者您好！还有一个问题就是缓存路径在Appdata，原来的小白羊好像是可以自定义的
> 
> 发现3.11.11版本已经可以自定义缓存路径啦！虽然下载的安装包还要安装，但其实已经可以当作便携版使用了！非常赞！

如何修改？

**Comment by Ghiclgi** [comment]
> > > 作者您好！还有一个问题就是缓存路径在Appdata，原来的小白羊好像是可以自定义的
> > 
> > 
> > 发现3.11.11版本已经可以自定义缓存路径啦！虽然下载的安装包还要安装，但其实已经可以当作便携版使用了！非常赞！
> 
> 如何修改？

后来的更新版本，已经无法修改了（作者去掉了这个功能）。不知道最新版本行不行
