### ISSUE TITLE
可否多加一些注释，同前端，正在拜读大佬的上传逻辑。 

### ISSUE THREAD

**Issue by zhengge791254521** [gaozhangmin/aliyunpan#75]
我也在做类似的上传功能，主要是类似阿里云这个大批量文件夹上传的整个前端部分逻辑，始终理不清楚。正好参考你的逻辑。
这里我有个疑惑，可能是我之前没有使用过MessageChannelMain的原因，我看你的代码，是创建了主进程和上传下载各自一个进程。 然后使用MessageChannelMain来互相通信，这样做有什么好处么。 

后续可以多一点注释么，三个进程在同一套前端代码里面，看得有点晕

**Comment by gaozhangmin** [comment]
这不是我的原始代码，我帮不了你。我也只是在慢慢重构原来的老代码
