### ISSUE TITLE
IINA 连续播放问题

### ISSUE THREAD

**Issue by spacding** [gaozhangmin/aliyunpan#78]
使用IINA作为播放器，在一个视频播放结束后关闭当前IINA窗口，再点击一个新的视频就无法调出IINA播放了，必须完全退出IINA，重新启动才能播放，请开发者解决下此问题，谢谢！

**Comment by spacding** [comment]
3.11.3无此问题，3.11.4及最新修复版都存在此问题

**Comment by gaozhangmin** [comment]
INNA是mac上的还是windows的播放器？我测下

**Comment by shareavave** [comment]
啊是的，新的版本调用 iina 打开文件时，需要在 iina 未运行的状态下才能顺利打开，否则会显示“loading...”然后切换到 iina 主界面之后便没反应了。
此时手动关闭 iina，然后再点击播放，让小白羊主动启动 iina 一次则可以顺利播放完当前文件。播放完之后，或者需要换集时，则需要再次手动关闭 iina 的进程，(关闭播放界面或关闭 iina 主界面都不信)，让小白羊重新调用才能顺利打开。
还请作者排查下缘由，巨大谢谢。

**Comment by spacding** [comment]
> 啊是的，新的版本调用 iina 打开文件时，需要在 iina 未运行的状态下才能顺利打开，否则会显示“loading...”然后切换到 iina 主界面之后便没反应了。 此时手动关闭 iina，然后再点击播放，让小白羊主动启动 iina 一次则可以顺利播放完当前文件。播放完之后，或者需要换集时，则需要再次手动关闭 iina 的进程，(关闭播放界面或关闭 iina 主界面都不信)，让小白羊重新调用才能顺利打开。 还请作者排查下缘由，巨大谢谢。

先退回3.11.3使用，等作者修复吧
