### ISSUE TITLE
v3.11.4fix版 上传文件出现505跳过不能秒传的文件

### ISSUE THREAD

**Issue by 454592673** [gaozhangmin/aliyunpan#79]
![微信截图_20230413094012](https://user-images.githubusercontent.com/22283930/231624396-85bd40ad-0b41-492e-832e-f8b94d2b635d.png)
已经过了hash校验，之后就是这个界面了

**Comment by cyao2q** [comment]
![image](https://user-images.githubusercontent.com/10820724/231637268-aae741bd-4670-42d2-ad25-a614854306cb.png)

**Comment by gaozhangmin** [comment]
秒传下个版本取消掉了 不支持 新版api
