### ISSUE TITLE
不能外挂云盘同目录下的字幕文件

### ISSUE THREAD

**Issue by qiulin6** [gaozhangmin/aliyunpan#8]
不能外挂云盘同目录下的字幕文件，最新的3.11版，播放器是potplayer 64位最新版。有什么解决办法吗？（除开下载到本地加载）

**Comment by gaozhangmin** [comment]
他怎么识别那个字幕文件对应哪个视频呢

**Comment by qiulin6** [comment]
比如，阿凡达2的视频和字幕文件，放在同一个文件夹中，并且命名一致。如果播放该视频文件，目前，不能加载字幕文件。不知道有什么解决方案没有。

**Comment by RinSky123** [comment]
> 要自己下载再加载，不是多一道手续么？ 小白云盘pc版的自带播放器字幕功能做到很好，能够完全加载外置及视频内封的字幕，但播放器界面不能全屏。 小白羊如果能够参照小白云盘pc版的字幕功能，那该多好啊。

小白羊那个网页内置播放器是可以识别字幕的，但是有点问题，它会显示不出来字幕，而且关闭播放器的时候会卡死，希望作者可以修复下

**Comment by gaozhangmin** [comment]
@RinSky123  这个我试过，能自动识别网盘同目录下的字幕文件的。目前只支持 srt|vtt|ass
