### ISSUE TITLE
啥时候支持下载m3u8

### ISSUE THREAD

**Issue by lanzhous** [gaozhangmin/aliyunpan#83]
啥时候支持下载m3u8

**Comment by gaozhangmin** [comment]
star下不过分吧？

**Comment by lanzhous** [comment]
有个下批量下载m3u8的那就是极好的。mkv转码过了，视频就好用了

**Comment by lanzhous** [comment]
> star下不过分吧？

点了点了

**Comment by maomaochong199** [comment]
想利用阿里云盘粗压视频，原来是很容易下载的，现在不会了，ts分片好像加了cdn验证F12看到的链接是一次性的了，我也想要下载视频预览的m3u8的功能

**Comment by gaozhangmin** [comment]
> 想利用阿里云盘粗压视频，原来是很容易下载的，现在不会了，ts分片好像加了cdn验证F12看到的链接是一次性的了，我也想要下载视频预览的m3u8的功能

我准备吧原作者没开发完成的下载m3u8视频功能给补上
