### ISSUE TITLE
同一文件不能秒传

### ISSUE THREAD

**Issue by six163** [gaozhangmin/aliyunpan#85]
我用旧版跟现在这个新版都试了一下，同一文件上传，用旧版就可以秒传，新版就要重新上传，是不是用了官方api的原因？

**Comment by gaozhangmin** [comment]
> 我用旧版跟现在这个新版都试了一下，同一文件上传，用旧版就可以秒传，新版就要重新上传，是不是用了官方api的原因？

不支持妙传 官方新api

**Comment by six163** [comment]
> > 我用旧版跟现在这个新版都试了一下，同一文件上传，用旧版就可以秒传，新版就要重新上传，是不是用了官方api的原因？
> 
> 不支持妙传 官方新API

明白了，谢谢大佬解答
