### ISSUE TITLE
上传总是出现 “ 505 分片上传失败，稍后重试read ECONNRESET ”  有小伙伴知道什么原因吗？

### ISSUE THREAD

**Issue by Michael-J-ScofieldOVO** [gaozhangmin/aliyunpan#92]
上传总是出现 “ 505 分片上传失败，稍后重试read ECONNRESET ”  有小伙伴知道什么原因吗？
![Snipaste_2023-04-18_20-31-12](https://user-images.githubusercontent.com/78257981/232778468-50e450c2-a4ab-46fc-a75b-56411fe7502b.jpg)

**Comment by gaozhangmin** [comment]
> 上传总是出现 “ 505 分片上传失败，稍后重试read ECONNRESET ”  有小伙伴知道什么原因吗？
> 
> ![Snipaste_2023-04-18_20-31-12](https://user-images.githubusercontent.com/78257981/232778468-50e450c2-a4ab-46fc-a75b-56411fe7502b.jpg)
> 
> 

看这是网络错误 网络质量不好吧

**Comment by yzw20020919** [comment]
我也遇到了，[
![屏幕截图 2024-06-06 220750](https://github.com/gaozhangmin/aliyunpan/assets/86851790/bba8fe97-6130-41c9-856d-d71627cf0c95)
](url)
有啥解决办法没？
