### ISSUE TITLE
视频标记失效

### ISSUE THREAD

**Issue by Violexjj** [gaozhangmin/aliyunpan#93]
已看过的视频标记功能失效了，大佬修复下吧

**Comment by gaozhangmin** [comment]
> 已看过的视频标记功能失效了，大佬修复下吧

放映室里面有已观看啊

**Comment by gaozhangmin** [comment]
> 已看过的视频标记功能失效了，大佬修复下吧
这个在我本地是有效的啊，你怎么说失效

**Comment by Violexjj** [comment]
> > 已看过的视频标记功能失效了，大佬修复下吧
> > 这个在我本地是有效的啊，你怎么说失效

不知道，反正我打开一集，马上返回小白羊看是有标记的。如果重启小白羊就没有标记了。
