### ISSUE TITLE
上传功能计算完sha1后，仍然进行普通上传

### ISSUE THREAD

**Issue by Huizs** [gaozhangmin/aliyunpan#94]
官方客户端或是原作者小白羊v3都可以sha1计算完成后上传完成，使用此版本则计算完sha1后继续网速普通上传
![image](https://user-images.githubusercontent.com/67303845/233026462-7f11cce5-50c9-407d-a40b-e4b8e7f0e91b.png)

**Comment by zksd2022** [comment]
+1 对比hash后无法秒传，希望作者修复

**Comment by LvTIanX** [comment]
+1
