### ISSUE TITLE
aria2连接失败问题

### ISSUE THREAD

**Issue by inmaker** [gaozhangmin/aliyunpan#98]
mac 上aria2连接失败问题。
版本：阿里云盘小白羊v3.11.5
系统：13.3
图1：
<img width="440" alt="Snipaste_2023-04-20_21-25-46" src="https://user-images.githubusercontent.com/78032377/233381868-ef243152-043f-4602-905b-ee887245e2a9.png">
>
图2：
<img width="477" alt="Snipaste_2023-04-20_21-27-08" src="https://user-images.githubusercontent.com/78032377/233381712-62c0c9b8-1af9-4a92-9ed3-b45767c054c2.png">

**Comment by haoyana** [comment]
同上

**Comment by jimmieyangcsjs** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/45389360/233532066-7de5b1cc-f1e2-444c-9cb7-38fb7b0844c2.png">
我这没问题。。看看说明吧 估计aria2没有装

**Comment by haoyana** [comment]
> <img width="550" alt="image" src="https://user-images.githubusercontent.com/45389360/233532066-7de5b1cc-f1e2-444c-9cb7-38fb7b0844c2.png">
> 
> 我这没问题。。看看说明吧 估计aria2没有装 

确实没安装，老哥方便简单指导一下嘛😂 谢谢您

**Comment by jimmieyangcsjs** [comment]
> > <img alt="image" width="550" src="https://user-images.githubusercontent.com/45389360/233532066-7de5b1cc-f1e2-444c-9cb7-38fb7b0844c2.png">
> > 我这没问题。。看看说明吧 估计aria2没有装
> 
> 确实没安装，老哥方便简单指导一下嘛😂 谢谢您

最简单的是先装brew  然后brew install  去安装aria2
